// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yandex/cloud/monitoring/v3/title_widget.proto

package yandex.cloud.api.monitoring.v3;

public final class TitleWidgetOuterClass {
  private TitleWidgetOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TitleWidgetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yandex.cloud.monitoring.v3.TitleWidget)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Title text.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <pre>
     * Title text.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <pre>
     * Title size.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
     * @return The enum numeric value on the wire for size.
     */
    int getSizeValue();
    /**
     * <pre>
     * Title size.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
     * @return The size.
     */
    yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize getSize();
  }
  /**
   * <pre>
   * Title widget.
   * </pre>
   *
   * Protobuf type {@code yandex.cloud.monitoring.v3.TitleWidget}
   */
  public static final class TitleWidget extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yandex.cloud.monitoring.v3.TitleWidget)
      TitleWidgetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TitleWidget.newBuilder() to construct.
    private TitleWidget(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TitleWidget() {
      text_ = "";
      size_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TitleWidget();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TitleWidget(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              size_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_TitleWidget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_TitleWidget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.class, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder.class);
    }

    /**
     * <pre>
     * Title size.
     * </pre>
     *
     * Protobuf enum {@code yandex.cloud.monitoring.v3.TitleWidget.TitleSize}
     */
    public enum TitleSize
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TITLE_SIZE_UNSPECIFIED = 0;</code>
       */
      TITLE_SIZE_UNSPECIFIED(0),
      /**
       * <pre>
       * Extra small size.
       * </pre>
       *
       * <code>TITLE_SIZE_XS = 1;</code>
       */
      TITLE_SIZE_XS(1),
      /**
       * <pre>
       * Small size.
       * </pre>
       *
       * <code>TITLE_SIZE_S = 2;</code>
       */
      TITLE_SIZE_S(2),
      /**
       * <pre>
       * Middle size.
       * </pre>
       *
       * <code>TITLE_SIZE_M = 3;</code>
       */
      TITLE_SIZE_M(3),
      /**
       * <pre>
       * Large size.
       * </pre>
       *
       * <code>TITLE_SIZE_L = 4;</code>
       */
      TITLE_SIZE_L(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TITLE_SIZE_UNSPECIFIED = 0;</code>
       */
      public static final int TITLE_SIZE_UNSPECIFIED_VALUE = 0;
      /**
       * <pre>
       * Extra small size.
       * </pre>
       *
       * <code>TITLE_SIZE_XS = 1;</code>
       */
      public static final int TITLE_SIZE_XS_VALUE = 1;
      /**
       * <pre>
       * Small size.
       * </pre>
       *
       * <code>TITLE_SIZE_S = 2;</code>
       */
      public static final int TITLE_SIZE_S_VALUE = 2;
      /**
       * <pre>
       * Middle size.
       * </pre>
       *
       * <code>TITLE_SIZE_M = 3;</code>
       */
      public static final int TITLE_SIZE_M_VALUE = 3;
      /**
       * <pre>
       * Large size.
       * </pre>
       *
       * <code>TITLE_SIZE_L = 4;</code>
       */
      public static final int TITLE_SIZE_L_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TitleSize valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TitleSize forNumber(int value) {
        switch (value) {
          case 0: return TITLE_SIZE_UNSPECIFIED;
          case 1: return TITLE_SIZE_XS;
          case 2: return TITLE_SIZE_S;
          case 3: return TITLE_SIZE_M;
          case 4: return TITLE_SIZE_L;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TitleSize>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TitleSize> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TitleSize>() {
              public TitleSize findValueByNumber(int number) {
                return TitleSize.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDescriptor().getEnumTypes().get(0);
      }

      private static final TitleSize[] VALUES = values();

      public static TitleSize valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TitleSize(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:yandex.cloud.monitoring.v3.TitleWidget.TitleSize)
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <pre>
     * Title text.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Title text.
     * </pre>
     *
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_;
    /**
     * <pre>
     * Title size.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
     * @return The enum numeric value on the wire for size.
     */
    @java.lang.Override public int getSizeValue() {
      return size_;
    }
    /**
     * <pre>
     * Title size.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
     * @return The size.
     */
    @java.lang.Override public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize getSize() {
      @SuppressWarnings("deprecation")
      yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize result = yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize.valueOf(size_);
      return result == null ? yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (size_ != yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize.TITLE_SIZE_UNSPECIFIED.getNumber()) {
        output.writeEnum(2, size_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (size_ != yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize.TITLE_SIZE_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget)) {
        return super.equals(obj);
      }
      yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget other = (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (size_ != other.size_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + size_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Title widget.
     * </pre>
     *
     * Protobuf type {@code yandex.cloud.monitoring.v3.TitleWidget}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yandex.cloud.monitoring.v3.TitleWidget)
        yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidgetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_TitleWidget_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_TitleWidget_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.class, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder.class);
      }

      // Construct using yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        text_ = "";

        size_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_TitleWidget_descriptor;
      }

      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget getDefaultInstanceForType() {
        return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance();
      }

      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget build() {
        yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget buildPartial() {
        yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget result = new yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget(this);
        result.text_ = text_;
        result.size_ = size_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) {
          return mergeFrom((yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget other) {
        if (other == yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (other.size_ != 0) {
          setSizeValue(other.getSizeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <pre>
       * Title text.
       * </pre>
       *
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Title text.
       * </pre>
       *
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Title text.
       * </pre>
       *
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Title text.
       * </pre>
       *
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Title text.
       * </pre>
       *
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private int size_ = 0;
      /**
       * <pre>
       * Title size.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
       * @return The enum numeric value on the wire for size.
       */
      @java.lang.Override public int getSizeValue() {
        return size_;
      }
      /**
       * <pre>
       * Title size.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
       * @param value The enum numeric value on the wire for size to set.
       * @return This builder for chaining.
       */
      public Builder setSizeValue(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Title size.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
       * @return The size.
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize getSize() {
        @SuppressWarnings("deprecation")
        yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize result = yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize.valueOf(size_);
        return result == null ? yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Title size.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.TitleSize value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        size_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Title size.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget.TitleSize size = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yandex.cloud.monitoring.v3.TitleWidget)
    }

    // @@protoc_insertion_point(class_scope:yandex.cloud.monitoring.v3.TitleWidget)
    private static final yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget();
    }

    public static yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TitleWidget>
        PARSER = new com.google.protobuf.AbstractParser<TitleWidget>() {
      @java.lang.Override
      public TitleWidget parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TitleWidget(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TitleWidget> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TitleWidget> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_monitoring_v3_TitleWidget_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_monitoring_v3_TitleWidget_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-yandex/cloud/monitoring/v3/title_widge" +
      "t.proto\022\032yandex.cloud.monitoring.v3\"\316\001\n\013" +
      "TitleWidget\022\014\n\004text\030\001 \001(\t\022?\n\004size\030\002 \001(\0162" +
      "1.yandex.cloud.monitoring.v3.TitleWidget" +
      ".TitleSize\"p\n\tTitleSize\022\032\n\026TITLE_SIZE_UN" +
      "SPECIFIED\020\000\022\021\n\rTITLE_SIZE_XS\020\001\022\020\n\014TITLE_" +
      "SIZE_S\020\002\022\020\n\014TITLE_SIZE_M\020\003\022\020\n\014TITLE_SIZE" +
      "_L\020\004Bk\n\036yandex.cloud.api.monitoring.v3ZI" +
      "github.com/yandex-cloud/go-genproto/yand" +
      "ex/cloud/monitoring/v3;monitoringb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yandex_cloud_monitoring_v3_TitleWidget_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yandex_cloud_monitoring_v3_TitleWidget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_monitoring_v3_TitleWidget_descriptor,
        new java.lang.String[] { "Text", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
