// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yandex/cloud/monitoring/v3/widget.proto

package yandex.cloud.api.monitoring.v3;

public final class WidgetOuterClass {
  private WidgetOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WidgetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yandex.cloud.monitoring.v3.Widget)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Required. Widget layout position.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
     * @return Whether the position field is set.
     */
    boolean hasPosition();
    /**
     * <pre>
     * Required. Widget layout position.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
     * @return The position.
     */
    yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition getPosition();
    /**
     * <pre>
     * Required. Widget layout position.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
     */
    yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPositionOrBuilder getPositionOrBuilder();

    /**
     * <pre>
     * Text widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
     * @return Whether the text field is set.
     */
    boolean hasText();
    /**
     * <pre>
     * Text widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
     * @return The text.
     */
    yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget getText();
    /**
     * <pre>
     * Text widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
     */
    yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidgetOrBuilder getTextOrBuilder();

    /**
     * <pre>
     * Title widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
     * @return Whether the title field is set.
     */
    boolean hasTitle();
    /**
     * <pre>
     * Title widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
     * @return The title.
     */
    yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget getTitle();
    /**
     * <pre>
     * Title widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
     */
    yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidgetOrBuilder getTitleOrBuilder();

    /**
     * <pre>
     * Chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
     * @return Whether the chart field is set.
     */
    boolean hasChart();
    /**
     * <pre>
     * Chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
     * @return The chart.
     */
    yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget getChart();
    /**
     * <pre>
     * Chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
     */
    yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidgetOrBuilder getChartOrBuilder();

    /**
     * <pre>
     * Multi-source chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
     * @return Whether the multiSourceChart field is set.
     */
    boolean hasMultiSourceChart();
    /**
     * <pre>
     * Multi-source chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
     * @return The multiSourceChart.
     */
    yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget getMultiSourceChart();
    /**
     * <pre>
     * Multi-source chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
     */
    yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidgetOrBuilder getMultiSourceChartOrBuilder();

    public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.WidgetCase getWidgetCase();
  }
  /**
   * <pre>
   * Widget.
   * </pre>
   *
   * Protobuf type {@code yandex.cloud.monitoring.v3.Widget}
   */
  public static final class Widget extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yandex.cloud.monitoring.v3.Widget)
      WidgetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Widget.newBuilder() to construct.
    private Widget(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Widget() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Widget();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Widget(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder subBuilder = null;
              if (position_ != null) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.Builder subBuilder = null;
              if (widgetCase_ == 2) {
                subBuilder = ((yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_).toBuilder();
              }
              widget_ =
                  input.readMessage(yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_);
                widget_ = subBuilder.buildPartial();
              }
              widgetCase_ = 2;
              break;
            }
            case 26: {
              yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder subBuilder = null;
              if (widgetCase_ == 3) {
                subBuilder = ((yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_).toBuilder();
              }
              widget_ =
                  input.readMessage(yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_);
                widget_ = subBuilder.buildPartial();
              }
              widgetCase_ = 3;
              break;
            }
            case 42: {
              yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.Builder subBuilder = null;
              if (widgetCase_ == 5) {
                subBuilder = ((yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_).toBuilder();
              }
              widget_ =
                  input.readMessage(yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_);
                widget_ = subBuilder.buildPartial();
              }
              widgetCase_ = 5;
              break;
            }
            case 50: {
              yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.Builder subBuilder = null;
              if (widgetCase_ == 6) {
                subBuilder = ((yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_).toBuilder();
              }
              widget_ =
                  input.readMessage(yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_);
                widget_ = subBuilder.buildPartial();
              }
              widgetCase_ = 6;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.class, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.Builder.class);
    }

    public interface LayoutPositionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:yandex.cloud.monitoring.v3.Widget.LayoutPosition)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * Required. X-axis top-left corner coordinate.
       * </pre>
       *
       * <code>int64 x = 1;</code>
       * @return The x.
       */
      long getX();

      /**
       * <pre>
       * Required. Y-axis top-left corner coordinate.
       * </pre>
       *
       * <code>int64 y = 2;</code>
       * @return The y.
       */
      long getY();

      /**
       * <pre>
       * Required. Weight.
       * </pre>
       *
       * <code>int64 w = 3;</code>
       * @return The w.
       */
      long getW();

      /**
       * <pre>
       * Required. Height.
       * </pre>
       *
       * <code>int64 h = 4;</code>
       * @return The h.
       */
      long getH();
    }
    /**
     * <pre>
     * Layout item for widget item positioning.
     * </pre>
     *
     * Protobuf type {@code yandex.cloud.monitoring.v3.Widget.LayoutPosition}
     */
    public static final class LayoutPosition extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:yandex.cloud.monitoring.v3.Widget.LayoutPosition)
        LayoutPositionOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use LayoutPosition.newBuilder() to construct.
      private LayoutPosition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private LayoutPosition() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new LayoutPosition();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private LayoutPosition(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                x_ = input.readInt64();
                break;
              }
              case 16: {

                y_ = input.readInt64();
                break;
              }
              case 24: {

                w_ = input.readInt64();
                break;
              }
              case 32: {

                h_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.class, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder.class);
      }

      public static final int X_FIELD_NUMBER = 1;
      private long x_;
      /**
       * <pre>
       * Required. X-axis top-left corner coordinate.
       * </pre>
       *
       * <code>int64 x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public long getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 2;
      private long y_;
      /**
       * <pre>
       * Required. Y-axis top-left corner coordinate.
       * </pre>
       *
       * <code>int64 y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public long getY() {
        return y_;
      }

      public static final int W_FIELD_NUMBER = 3;
      private long w_;
      /**
       * <pre>
       * Required. Weight.
       * </pre>
       *
       * <code>int64 w = 3;</code>
       * @return The w.
       */
      @java.lang.Override
      public long getW() {
        return w_;
      }

      public static final int H_FIELD_NUMBER = 4;
      private long h_;
      /**
       * <pre>
       * Required. Height.
       * </pre>
       *
       * <code>int64 h = 4;</code>
       * @return The h.
       */
      @java.lang.Override
      public long getH() {
        return h_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (x_ != 0L) {
          output.writeInt64(1, x_);
        }
        if (y_ != 0L) {
          output.writeInt64(2, y_);
        }
        if (w_ != 0L) {
          output.writeInt64(3, w_);
        }
        if (h_ != 0L) {
          output.writeInt64(4, h_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (x_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, x_);
        }
        if (y_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, y_);
        }
        if (w_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, w_);
        }
        if (h_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, h_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition)) {
          return super.equals(obj);
        }
        yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition other = (yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition) obj;

        if (getX()
            != other.getX()) return false;
        if (getY()
            != other.getY()) return false;
        if (getW()
            != other.getW()) return false;
        if (getH()
            != other.getH()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getX());
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getY());
        hash = (37 * hash) + W_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getW());
        hash = (37 * hash) + H_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getH());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Layout item for widget item positioning.
       * </pre>
       *
       * Protobuf type {@code yandex.cloud.monitoring.v3.Widget.LayoutPosition}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:yandex.cloud.monitoring.v3.Widget.LayoutPosition)
          yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPositionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.class, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder.class);
        }

        // Construct using yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          x_ = 0L;

          y_ = 0L;

          w_ = 0L;

          h_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_descriptor;
        }

        @java.lang.Override
        public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition getDefaultInstanceForType() {
          return yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.getDefaultInstance();
        }

        @java.lang.Override
        public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition build() {
          yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition buildPartial() {
          yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition result = new yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition(this);
          result.x_ = x_;
          result.y_ = y_;
          result.w_ = w_;
          result.h_ = h_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition) {
            return mergeFrom((yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition other) {
          if (other == yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.getDefaultInstance()) return this;
          if (other.getX() != 0L) {
            setX(other.getX());
          }
          if (other.getY() != 0L) {
            setY(other.getY());
          }
          if (other.getW() != 0L) {
            setW(other.getW());
          }
          if (other.getH() != 0L) {
            setH(other.getH());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long x_ ;
        /**
         * <pre>
         * Required. X-axis top-left corner coordinate.
         * </pre>
         *
         * <code>int64 x = 1;</code>
         * @return The x.
         */
        @java.lang.Override
        public long getX() {
          return x_;
        }
        /**
         * <pre>
         * Required. X-axis top-left corner coordinate.
         * </pre>
         *
         * <code>int64 x = 1;</code>
         * @param value The x to set.
         * @return This builder for chaining.
         */
        public Builder setX(long value) {
          
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Required. X-axis top-left corner coordinate.
         * </pre>
         *
         * <code>int64 x = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearX() {
          
          x_ = 0L;
          onChanged();
          return this;
        }

        private long y_ ;
        /**
         * <pre>
         * Required. Y-axis top-left corner coordinate.
         * </pre>
         *
         * <code>int64 y = 2;</code>
         * @return The y.
         */
        @java.lang.Override
        public long getY() {
          return y_;
        }
        /**
         * <pre>
         * Required. Y-axis top-left corner coordinate.
         * </pre>
         *
         * <code>int64 y = 2;</code>
         * @param value The y to set.
         * @return This builder for chaining.
         */
        public Builder setY(long value) {
          
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Required. Y-axis top-left corner coordinate.
         * </pre>
         *
         * <code>int64 y = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearY() {
          
          y_ = 0L;
          onChanged();
          return this;
        }

        private long w_ ;
        /**
         * <pre>
         * Required. Weight.
         * </pre>
         *
         * <code>int64 w = 3;</code>
         * @return The w.
         */
        @java.lang.Override
        public long getW() {
          return w_;
        }
        /**
         * <pre>
         * Required. Weight.
         * </pre>
         *
         * <code>int64 w = 3;</code>
         * @param value The w to set.
         * @return This builder for chaining.
         */
        public Builder setW(long value) {
          
          w_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Required. Weight.
         * </pre>
         *
         * <code>int64 w = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearW() {
          
          w_ = 0L;
          onChanged();
          return this;
        }

        private long h_ ;
        /**
         * <pre>
         * Required. Height.
         * </pre>
         *
         * <code>int64 h = 4;</code>
         * @return The h.
         */
        @java.lang.Override
        public long getH() {
          return h_;
        }
        /**
         * <pre>
         * Required. Height.
         * </pre>
         *
         * <code>int64 h = 4;</code>
         * @param value The h to set.
         * @return This builder for chaining.
         */
        public Builder setH(long value) {
          
          h_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Required. Height.
         * </pre>
         *
         * <code>int64 h = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearH() {
          
          h_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:yandex.cloud.monitoring.v3.Widget.LayoutPosition)
      }

      // @@protoc_insertion_point(class_scope:yandex.cloud.monitoring.v3.Widget.LayoutPosition)
      private static final yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition();
      }

      public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<LayoutPosition>
          PARSER = new com.google.protobuf.AbstractParser<LayoutPosition>() {
        @java.lang.Override
        public LayoutPosition parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LayoutPosition(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<LayoutPosition> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<LayoutPosition> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int widgetCase_ = 0;
    private java.lang.Object widget_;
    public enum WidgetCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      TEXT(2),
      TITLE(3),
      CHART(5),
      MULTI_SOURCE_CHART(6),
      WIDGET_NOT_SET(0);
      private final int value;
      private WidgetCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WidgetCase valueOf(int value) {
        return forNumber(value);
      }

      public static WidgetCase forNumber(int value) {
        switch (value) {
          case 2: return TEXT;
          case 3: return TITLE;
          case 5: return CHART;
          case 6: return MULTI_SOURCE_CHART;
          case 0: return WIDGET_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public WidgetCase
    getWidgetCase() {
      return WidgetCase.forNumber(
          widgetCase_);
    }

    public static final int POSITION_FIELD_NUMBER = 1;
    private yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition position_;
    /**
     * <pre>
     * Required. Widget layout position.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
     * @return Whether the position field is set.
     */
    @java.lang.Override
    public boolean hasPosition() {
      return position_ != null;
    }
    /**
     * <pre>
     * Required. Widget layout position.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
     * @return The position.
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition getPosition() {
      return position_ == null ? yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.getDefaultInstance() : position_;
    }
    /**
     * <pre>
     * Required. Widget layout position.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPositionOrBuilder getPositionOrBuilder() {
      return getPosition();
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    /**
     * <pre>
     * Text widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return widgetCase_ == 2;
    }
    /**
     * <pre>
     * Text widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
     * @return The text.
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget getText() {
      if (widgetCase_ == 2) {
         return (yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.getDefaultInstance();
    }
    /**
     * <pre>
     * Text widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidgetOrBuilder getTextOrBuilder() {
      if (widgetCase_ == 2) {
         return (yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.getDefaultInstance();
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    /**
     * <pre>
     * Title widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
     * @return Whether the title field is set.
     */
    @java.lang.Override
    public boolean hasTitle() {
      return widgetCase_ == 3;
    }
    /**
     * <pre>
     * Title widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
     * @return The title.
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget getTitle() {
      if (widgetCase_ == 3) {
         return (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance();
    }
    /**
     * <pre>
     * Title widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidgetOrBuilder getTitleOrBuilder() {
      if (widgetCase_ == 3) {
         return (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance();
    }

    public static final int CHART_FIELD_NUMBER = 5;
    /**
     * <pre>
     * Chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
     * @return Whether the chart field is set.
     */
    @java.lang.Override
    public boolean hasChart() {
      return widgetCase_ == 5;
    }
    /**
     * <pre>
     * Chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
     * @return The chart.
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget getChart() {
      if (widgetCase_ == 5) {
         return (yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.getDefaultInstance();
    }
    /**
     * <pre>
     * Chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidgetOrBuilder getChartOrBuilder() {
      if (widgetCase_ == 5) {
         return (yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.getDefaultInstance();
    }

    public static final int MULTI_SOURCE_CHART_FIELD_NUMBER = 6;
    /**
     * <pre>
     * Multi-source chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
     * @return Whether the multiSourceChart field is set.
     */
    @java.lang.Override
    public boolean hasMultiSourceChart() {
      return widgetCase_ == 6;
    }
    /**
     * <pre>
     * Multi-source chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
     * @return The multiSourceChart.
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget getMultiSourceChart() {
      if (widgetCase_ == 6) {
         return (yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.getDefaultInstance();
    }
    /**
     * <pre>
     * Multi-source chart widget.
     * </pre>
     *
     * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
     */
    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidgetOrBuilder getMultiSourceChartOrBuilder() {
      if (widgetCase_ == 6) {
         return (yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_;
      }
      return yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (position_ != null) {
        output.writeMessage(1, getPosition());
      }
      if (widgetCase_ == 2) {
        output.writeMessage(2, (yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_);
      }
      if (widgetCase_ == 3) {
        output.writeMessage(3, (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_);
      }
      if (widgetCase_ == 5) {
        output.writeMessage(5, (yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_);
      }
      if (widgetCase_ == 6) {
        output.writeMessage(6, (yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (position_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPosition());
      }
      if (widgetCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_);
      }
      if (widgetCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_);
      }
      if (widgetCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_);
      }
      if (widgetCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget)) {
        return super.equals(obj);
      }
      yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget other = (yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget) obj;

      if (hasPosition() != other.hasPosition()) return false;
      if (hasPosition()) {
        if (!getPosition()
            .equals(other.getPosition())) return false;
      }
      if (!getWidgetCase().equals(other.getWidgetCase())) return false;
      switch (widgetCase_) {
        case 2:
          if (!getText()
              .equals(other.getText())) return false;
          break;
        case 3:
          if (!getTitle()
              .equals(other.getTitle())) return false;
          break;
        case 5:
          if (!getChart()
              .equals(other.getChart())) return false;
          break;
        case 6:
          if (!getMultiSourceChart()
              .equals(other.getMultiSourceChart())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPosition()) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPosition().hashCode();
      }
      switch (widgetCase_) {
        case 2:
          hash = (37 * hash) + TEXT_FIELD_NUMBER;
          hash = (53 * hash) + getText().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TITLE_FIELD_NUMBER;
          hash = (53 * hash) + getTitle().hashCode();
          break;
        case 5:
          hash = (37 * hash) + CHART_FIELD_NUMBER;
          hash = (53 * hash) + getChart().hashCode();
          break;
        case 6:
          hash = (37 * hash) + MULTI_SOURCE_CHART_FIELD_NUMBER;
          hash = (53 * hash) + getMultiSourceChart().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Widget.
     * </pre>
     *
     * Protobuf type {@code yandex.cloud.monitoring.v3.Widget}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yandex.cloud.monitoring.v3.Widget)
        yandex.cloud.api.monitoring.v3.WidgetOuterClass.WidgetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.class, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.Builder.class);
      }

      // Construct using yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (positionBuilder_ == null) {
          position_ = null;
        } else {
          position_ = null;
          positionBuilder_ = null;
        }
        widgetCase_ = 0;
        widget_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yandex.cloud.api.monitoring.v3.WidgetOuterClass.internal_static_yandex_cloud_monitoring_v3_Widget_descriptor;
      }

      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget getDefaultInstanceForType() {
        return yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.getDefaultInstance();
      }

      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget build() {
        yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget buildPartial() {
        yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget result = new yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget(this);
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        if (widgetCase_ == 2) {
          if (textBuilder_ == null) {
            result.widget_ = widget_;
          } else {
            result.widget_ = textBuilder_.build();
          }
        }
        if (widgetCase_ == 3) {
          if (titleBuilder_ == null) {
            result.widget_ = widget_;
          } else {
            result.widget_ = titleBuilder_.build();
          }
        }
        if (widgetCase_ == 5) {
          if (chartBuilder_ == null) {
            result.widget_ = widget_;
          } else {
            result.widget_ = chartBuilder_.build();
          }
        }
        if (widgetCase_ == 6) {
          if (multiSourceChartBuilder_ == null) {
            result.widget_ = widget_;
          } else {
            result.widget_ = multiSourceChartBuilder_.build();
          }
        }
        result.widgetCase_ = widgetCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget) {
          return mergeFrom((yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget other) {
        if (other == yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.getDefaultInstance()) return this;
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        switch (other.getWidgetCase()) {
          case TEXT: {
            mergeText(other.getText());
            break;
          }
          case TITLE: {
            mergeTitle(other.getTitle());
            break;
          }
          case CHART: {
            mergeChart(other.getChart());
            break;
          }
          case MULTI_SOURCE_CHART: {
            mergeMultiSourceChart(other.getMultiSourceChart());
            break;
          }
          case WIDGET_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int widgetCase_ = 0;
      private java.lang.Object widget_;
      public WidgetCase
          getWidgetCase() {
        return WidgetCase.forNumber(
            widgetCase_);
      }

      public Builder clearWidget() {
        widgetCase_ = 0;
        widget_ = null;
        onChanged();
        return this;
      }


      private yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition position_;
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPositionOrBuilder> positionBuilder_;
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       * @return Whether the position field is set.
       */
      public boolean hasPosition() {
        return positionBuilder_ != null || position_ != null;
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       * @return The position.
       */
      public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition getPosition() {
        if (positionBuilder_ == null) {
          return position_ == null ? yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.getDefaultInstance() : position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       */
      public Builder setPosition(yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       */
      public Builder setPosition(
          yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       */
      public Builder mergePosition(yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition value) {
        if (positionBuilder_ == null) {
          if (position_ != null) {
            position_ =
              yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = null;
          onChanged();
        } else {
          position_ = null;
          positionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       */
      public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder getPositionBuilder() {
        
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       */
      public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_ == null ?
              yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.getDefaultInstance() : position_;
        }
      }
      /**
       * <pre>
       * Required. Widget layout position.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.Widget.LayoutPosition position = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPositionOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPosition.Builder, yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget.LayoutPositionOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget, yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.Builder, yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidgetOrBuilder> textBuilder_;
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       * @return Whether the text field is set.
       */
      @java.lang.Override
      public boolean hasText() {
        return widgetCase_ == 2;
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       * @return The text.
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget getText() {
        if (textBuilder_ == null) {
          if (widgetCase_ == 2) {
            return (yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.getDefaultInstance();
        } else {
          if (widgetCase_ == 2) {
            return textBuilder_.getMessage();
          }
          return yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       */
      public Builder setText(yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget value) {
        if (textBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          widget_ = value;
          onChanged();
        } else {
          textBuilder_.setMessage(value);
        }
        widgetCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       */
      public Builder setText(
          yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.Builder builderForValue) {
        if (textBuilder_ == null) {
          widget_ = builderForValue.build();
          onChanged();
        } else {
          textBuilder_.setMessage(builderForValue.build());
        }
        widgetCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       */
      public Builder mergeText(yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget value) {
        if (textBuilder_ == null) {
          if (widgetCase_ == 2 &&
              widget_ != yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.getDefaultInstance()) {
            widget_ = yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.newBuilder((yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_)
                .mergeFrom(value).buildPartial();
          } else {
            widget_ = value;
          }
          onChanged();
        } else {
          if (widgetCase_ == 2) {
            textBuilder_.mergeFrom(value);
          }
          textBuilder_.setMessage(value);
        }
        widgetCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       */
      public Builder clearText() {
        if (textBuilder_ == null) {
          if (widgetCase_ == 2) {
            widgetCase_ = 0;
            widget_ = null;
            onChanged();
          }
        } else {
          if (widgetCase_ == 2) {
            widgetCase_ = 0;
            widget_ = null;
          }
          textBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       */
      public yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.Builder getTextBuilder() {
        return getTextFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidgetOrBuilder getTextOrBuilder() {
        if ((widgetCase_ == 2) && (textBuilder_ != null)) {
          return textBuilder_.getMessageOrBuilder();
        } else {
          if (widgetCase_ == 2) {
            return (yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Text widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TextWidget text = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget, yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.Builder, yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidgetOrBuilder> 
          getTextFieldBuilder() {
        if (textBuilder_ == null) {
          if (!(widgetCase_ == 2)) {
            widget_ = yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.getDefaultInstance();
          }
          textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget, yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget.Builder, yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidgetOrBuilder>(
                  (yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.TextWidget) widget_,
                  getParentForChildren(),
                  isClean());
          widget_ = null;
        }
        widgetCase_ = 2;
        onChanged();;
        return textBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidgetOrBuilder> titleBuilder_;
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       * @return Whether the title field is set.
       */
      @java.lang.Override
      public boolean hasTitle() {
        return widgetCase_ == 3;
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       * @return The title.
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget getTitle() {
        if (titleBuilder_ == null) {
          if (widgetCase_ == 3) {
            return (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance();
        } else {
          if (widgetCase_ == 3) {
            return titleBuilder_.getMessage();
          }
          return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       */
      public Builder setTitle(yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget value) {
        if (titleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          widget_ = value;
          onChanged();
        } else {
          titleBuilder_.setMessage(value);
        }
        widgetCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       */
      public Builder setTitle(
          yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder builderForValue) {
        if (titleBuilder_ == null) {
          widget_ = builderForValue.build();
          onChanged();
        } else {
          titleBuilder_.setMessage(builderForValue.build());
        }
        widgetCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       */
      public Builder mergeTitle(yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget value) {
        if (titleBuilder_ == null) {
          if (widgetCase_ == 3 &&
              widget_ != yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance()) {
            widget_ = yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.newBuilder((yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_)
                .mergeFrom(value).buildPartial();
          } else {
            widget_ = value;
          }
          onChanged();
        } else {
          if (widgetCase_ == 3) {
            titleBuilder_.mergeFrom(value);
          }
          titleBuilder_.setMessage(value);
        }
        widgetCase_ = 3;
        return this;
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       */
      public Builder clearTitle() {
        if (titleBuilder_ == null) {
          if (widgetCase_ == 3) {
            widgetCase_ = 0;
            widget_ = null;
            onChanged();
          }
        } else {
          if (widgetCase_ == 3) {
            widgetCase_ = 0;
            widget_ = null;
          }
          titleBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       */
      public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder getTitleBuilder() {
        return getTitleFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidgetOrBuilder getTitleOrBuilder() {
        if ((widgetCase_ == 3) && (titleBuilder_ != null)) {
          return titleBuilder_.getMessageOrBuilder();
        } else {
          if (widgetCase_ == 3) {
            return (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Title widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.TitleWidget title = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidgetOrBuilder> 
          getTitleFieldBuilder() {
        if (titleBuilder_ == null) {
          if (!(widgetCase_ == 3)) {
            widget_ = yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.getDefaultInstance();
          }
          titleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget.Builder, yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidgetOrBuilder>(
                  (yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.TitleWidget) widget_,
                  getParentForChildren(),
                  isClean());
          widget_ = null;
        }
        widgetCase_ = 3;
        onChanged();;
        return titleBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget, yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.Builder, yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidgetOrBuilder> chartBuilder_;
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       * @return Whether the chart field is set.
       */
      @java.lang.Override
      public boolean hasChart() {
        return widgetCase_ == 5;
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       * @return The chart.
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget getChart() {
        if (chartBuilder_ == null) {
          if (widgetCase_ == 5) {
            return (yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.getDefaultInstance();
        } else {
          if (widgetCase_ == 5) {
            return chartBuilder_.getMessage();
          }
          return yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       */
      public Builder setChart(yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget value) {
        if (chartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          widget_ = value;
          onChanged();
        } else {
          chartBuilder_.setMessage(value);
        }
        widgetCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       */
      public Builder setChart(
          yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.Builder builderForValue) {
        if (chartBuilder_ == null) {
          widget_ = builderForValue.build();
          onChanged();
        } else {
          chartBuilder_.setMessage(builderForValue.build());
        }
        widgetCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       */
      public Builder mergeChart(yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget value) {
        if (chartBuilder_ == null) {
          if (widgetCase_ == 5 &&
              widget_ != yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.getDefaultInstance()) {
            widget_ = yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.newBuilder((yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_)
                .mergeFrom(value).buildPartial();
          } else {
            widget_ = value;
          }
          onChanged();
        } else {
          if (widgetCase_ == 5) {
            chartBuilder_.mergeFrom(value);
          }
          chartBuilder_.setMessage(value);
        }
        widgetCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       */
      public Builder clearChart() {
        if (chartBuilder_ == null) {
          if (widgetCase_ == 5) {
            widgetCase_ = 0;
            widget_ = null;
            onChanged();
          }
        } else {
          if (widgetCase_ == 5) {
            widgetCase_ = 0;
            widget_ = null;
          }
          chartBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       */
      public yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.Builder getChartBuilder() {
        return getChartFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidgetOrBuilder getChartOrBuilder() {
        if ((widgetCase_ == 5) && (chartBuilder_ != null)) {
          return chartBuilder_.getMessageOrBuilder();
        } else {
          if (widgetCase_ == 5) {
            return (yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.ChartWidget chart = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget, yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.Builder, yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidgetOrBuilder> 
          getChartFieldBuilder() {
        if (chartBuilder_ == null) {
          if (!(widgetCase_ == 5)) {
            widget_ = yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.getDefaultInstance();
          }
          chartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget, yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget.Builder, yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidgetOrBuilder>(
                  (yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.ChartWidget) widget_,
                  getParentForChildren(),
                  isClean());
          widget_ = null;
        }
        widgetCase_ = 5;
        onChanged();;
        return chartBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget, yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.Builder, yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidgetOrBuilder> multiSourceChartBuilder_;
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       * @return Whether the multiSourceChart field is set.
       */
      @java.lang.Override
      public boolean hasMultiSourceChart() {
        return widgetCase_ == 6;
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       * @return The multiSourceChart.
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget getMultiSourceChart() {
        if (multiSourceChartBuilder_ == null) {
          if (widgetCase_ == 6) {
            return (yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.getDefaultInstance();
        } else {
          if (widgetCase_ == 6) {
            return multiSourceChartBuilder_.getMessage();
          }
          return yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       */
      public Builder setMultiSourceChart(yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget value) {
        if (multiSourceChartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          widget_ = value;
          onChanged();
        } else {
          multiSourceChartBuilder_.setMessage(value);
        }
        widgetCase_ = 6;
        return this;
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       */
      public Builder setMultiSourceChart(
          yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.Builder builderForValue) {
        if (multiSourceChartBuilder_ == null) {
          widget_ = builderForValue.build();
          onChanged();
        } else {
          multiSourceChartBuilder_.setMessage(builderForValue.build());
        }
        widgetCase_ = 6;
        return this;
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       */
      public Builder mergeMultiSourceChart(yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget value) {
        if (multiSourceChartBuilder_ == null) {
          if (widgetCase_ == 6 &&
              widget_ != yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.getDefaultInstance()) {
            widget_ = yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.newBuilder((yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_)
                .mergeFrom(value).buildPartial();
          } else {
            widget_ = value;
          }
          onChanged();
        } else {
          if (widgetCase_ == 6) {
            multiSourceChartBuilder_.mergeFrom(value);
          }
          multiSourceChartBuilder_.setMessage(value);
        }
        widgetCase_ = 6;
        return this;
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       */
      public Builder clearMultiSourceChart() {
        if (multiSourceChartBuilder_ == null) {
          if (widgetCase_ == 6) {
            widgetCase_ = 0;
            widget_ = null;
            onChanged();
          }
        } else {
          if (widgetCase_ == 6) {
            widgetCase_ = 0;
            widget_ = null;
          }
          multiSourceChartBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       */
      public yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.Builder getMultiSourceChartBuilder() {
        return getMultiSourceChartFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       */
      @java.lang.Override
      public yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidgetOrBuilder getMultiSourceChartOrBuilder() {
        if ((widgetCase_ == 6) && (multiSourceChartBuilder_ != null)) {
          return multiSourceChartBuilder_.getMessageOrBuilder();
        } else {
          if (widgetCase_ == 6) {
            return (yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_;
          }
          return yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * Multi-source chart widget.
       * </pre>
       *
       * <code>.yandex.cloud.monitoring.v3.MultiSourceChartWidget multi_source_chart = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget, yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.Builder, yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidgetOrBuilder> 
          getMultiSourceChartFieldBuilder() {
        if (multiSourceChartBuilder_ == null) {
          if (!(widgetCase_ == 6)) {
            widget_ = yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.getDefaultInstance();
          }
          multiSourceChartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget, yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget.Builder, yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidgetOrBuilder>(
                  (yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.MultiSourceChartWidget) widget_,
                  getParentForChildren(),
                  isClean());
          widget_ = null;
        }
        widgetCase_ = 6;
        onChanged();;
        return multiSourceChartBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yandex.cloud.monitoring.v3.Widget)
    }

    // @@protoc_insertion_point(class_scope:yandex.cloud.monitoring.v3.Widget)
    private static final yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget();
    }

    public static yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Widget>
        PARSER = new com.google.protobuf.AbstractParser<Widget>() {
      @java.lang.Override
      public Widget parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Widget(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Widget> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Widget> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yandex.cloud.api.monitoring.v3.WidgetOuterClass.Widget getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_monitoring_v3_Widget_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_monitoring_v3_Widget_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'yandex/cloud/monitoring/v3/widget.prot" +
      "o\022\032yandex.cloud.monitoring.v3\032-yandex/cl" +
      "oud/monitoring/v3/chart_widget.proto\032,ya" +
      "ndex/cloud/monitoring/v3/text_widget.pro" +
      "to\032-yandex/cloud/monitoring/v3/title_wid" +
      "get.proto\032:yandex/cloud/monitoring/v3/mu" +
      "lti_source_chart_widget.proto\"\231\003\n\006Widget" +
      "\022C\n\010position\030\001 \001(\01321.yandex.cloud.monito" +
      "ring.v3.Widget.LayoutPosition\0226\n\004text\030\002 " +
      "\001(\0132&.yandex.cloud.monitoring.v3.TextWid" +
      "getH\000\0228\n\005title\030\003 \001(\0132\'.yandex.cloud.moni" +
      "toring.v3.TitleWidgetH\000\0228\n\005chart\030\005 \001(\0132\'" +
      ".yandex.cloud.monitoring.v3.ChartWidgetH" +
      "\000\022P\n\022multi_source_chart\030\006 \001(\01322.yandex.c" +
      "loud.monitoring.v3.MultiSourceChartWidge" +
      "tH\000\032<\n\016LayoutPosition\022\t\n\001x\030\001 \001(\003\022\t\n\001y\030\002 " +
      "\001(\003\022\t\n\001w\030\003 \001(\003\022\t\n\001h\030\004 \001(\003B\010\n\006widgetJ\004\010\004\020" +
      "\005Bk\n\036yandex.cloud.api.monitoring.v3ZIgit" +
      "hub.com/yandex-cloud/go-genproto/yandex/" +
      "cloud/monitoring/v3;monitoringb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.getDescriptor(),
          yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.getDescriptor(),
          yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.getDescriptor(),
          yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.getDescriptor(),
        });
    internal_static_yandex_cloud_monitoring_v3_Widget_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yandex_cloud_monitoring_v3_Widget_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_monitoring_v3_Widget_descriptor,
        new java.lang.String[] { "Position", "Text", "Title", "Chart", "MultiSourceChart", "Widget", });
    internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_descriptor =
      internal_static_yandex_cloud_monitoring_v3_Widget_descriptor.getNestedTypes().get(0);
    internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_monitoring_v3_Widget_LayoutPosition_descriptor,
        new java.lang.String[] { "X", "Y", "W", "H", });
    yandex.cloud.api.monitoring.v3.ChartWidgetOuterClass.getDescriptor();
    yandex.cloud.api.monitoring.v3.TextWidgetOuterClass.getDescriptor();
    yandex.cloud.api.monitoring.v3.TitleWidgetOuterClass.getDescriptor();
    yandex.cloud.api.monitoring.v3.MultiSourceChartWidgetOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
