// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yandex/cloud/iam/v1/awscompatibility/access_key.proto

package yandex.cloud.api.iam.v1.awscompatibility;

public final class AccessKeyOuterClass {
  private AccessKeyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccessKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yandex.cloud.iam.v1.awscompatibility.AccessKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ID of the AccessKey resource.
     * It is used to manage secret credentials: an access key ID and a secret access key.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * ID of the AccessKey resource.
     * It is used to manage secret credentials: an access key ID and a secret access key.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * ID of the service account that the access key belongs to.
     * </pre>
     *
     * <code>string service_account_id = 2;</code>
     * @return The serviceAccountId.
     */
    java.lang.String getServiceAccountId();
    /**
     * <pre>
     * ID of the service account that the access key belongs to.
     * </pre>
     *
     * <code>string service_account_id = 2;</code>
     * @return The bytes for serviceAccountId.
     */
    com.google.protobuf.ByteString
        getServiceAccountIdBytes();

    /**
     * <pre>
     * Creation timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <pre>
     * Creation timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
    /**
     * <pre>
     * Creation timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

    /**
     * <pre>
     * Description of the access key. 0-256 characters long.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <pre>
     * Description of the access key. 0-256 characters long.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     * ID of the access key.
     * The key is AWS compatible.
     * </pre>
     *
     * <code>string key_id = 5;</code>
     * @return The keyId.
     */
    java.lang.String getKeyId();
    /**
     * <pre>
     * ID of the access key.
     * The key is AWS compatible.
     * </pre>
     *
     * <code>string key_id = 5;</code>
     * @return The bytes for keyId.
     */
    com.google.protobuf.ByteString
        getKeyIdBytes();

    /**
     * <pre>
     * Timestamp for the last authentication using this Access key.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
     * @return Whether the lastUsedAt field is set.
     */
    boolean hasLastUsedAt();
    /**
     * <pre>
     * Timestamp for the last authentication using this Access key.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
     * @return The lastUsedAt.
     */
    com.google.protobuf.Timestamp getLastUsedAt();
    /**
     * <pre>
     * Timestamp for the last authentication using this Access key.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getLastUsedAtOrBuilder();
  }
  /**
   * <pre>
   * An access key.
   * For more information, see [AWS-compatible access keys](/docs/iam/concepts/authorization/access-key).
   * </pre>
   *
   * Protobuf type {@code yandex.cloud.iam.v1.awscompatibility.AccessKey}
   */
  public static final class AccessKey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yandex.cloud.iam.v1.awscompatibility.AccessKey)
      AccessKeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccessKey.newBuilder() to construct.
    private AccessKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccessKey() {
      id_ = "";
      serviceAccountId_ = "";
      description_ = "";
      keyId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccessKey();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AccessKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceAccountId_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (createdAt_ != null) {
                subBuilder = createdAt_.toBuilder();
              }
              createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createdAt_);
                createdAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              keyId_ = s;
              break;
            }
            case 58: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (lastUsedAt_ != null) {
                subBuilder = lastUsedAt_.toBuilder();
              }
              lastUsedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastUsedAt_);
                lastUsedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey.class, yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <pre>
     * ID of the AccessKey resource.
     * It is used to manage secret credentials: an access key ID and a secret access key.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ID of the AccessKey resource.
     * It is used to manage secret credentials: an access key ID and a secret access key.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_ACCOUNT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object serviceAccountId_;
    /**
     * <pre>
     * ID of the service account that the access key belongs to.
     * </pre>
     *
     * <code>string service_account_id = 2;</code>
     * @return The serviceAccountId.
     */
    @java.lang.Override
    public java.lang.String getServiceAccountId() {
      java.lang.Object ref = serviceAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceAccountId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ID of the service account that the access key belongs to.
     * </pre>
     *
     * <code>string service_account_id = 2;</code>
     * @return The bytes for serviceAccountId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceAccountIdBytes() {
      java.lang.Object ref = serviceAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_AT_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <pre>
     * Creation timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return createdAt_ != null;
    }
    /**
     * <pre>
     * Creation timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <pre>
     * Creation timestamp.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      return getCreatedAt();
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <pre>
     * Description of the access key. 0-256 characters long.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Description of the access key. 0-256 characters long.
     * </pre>
     *
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object keyId_;
    /**
     * <pre>
     * ID of the access key.
     * The key is AWS compatible.
     * </pre>
     *
     * <code>string key_id = 5;</code>
     * @return The keyId.
     */
    @java.lang.Override
    public java.lang.String getKeyId() {
      java.lang.Object ref = keyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * ID of the access key.
     * The key is AWS compatible.
     * </pre>
     *
     * <code>string key_id = 5;</code>
     * @return The bytes for keyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyIdBytes() {
      java.lang.Object ref = keyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_USED_AT_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp lastUsedAt_;
    /**
     * <pre>
     * Timestamp for the last authentication using this Access key.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
     * @return Whether the lastUsedAt field is set.
     */
    @java.lang.Override
    public boolean hasLastUsedAt() {
      return lastUsedAt_ != null;
    }
    /**
     * <pre>
     * Timestamp for the last authentication using this Access key.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
     * @return The lastUsedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLastUsedAt() {
      return lastUsedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUsedAt_;
    }
    /**
     * <pre>
     * Timestamp for the last authentication using this Access key.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getLastUsedAtOrBuilder() {
      return getLastUsedAt();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceAccountId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceAccountId_);
      }
      if (createdAt_ != null) {
        output.writeMessage(3, getCreatedAt());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, keyId_);
      }
      if (lastUsedAt_ != null) {
        output.writeMessage(7, getLastUsedAt());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceAccountId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceAccountId_);
      }
      if (createdAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCreatedAt());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, keyId_);
      }
      if (lastUsedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getLastUsedAt());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey)) {
        return super.equals(obj);
      }
      yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey other = (yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getServiceAccountId()
          .equals(other.getServiceAccountId())) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getKeyId()
          .equals(other.getKeyId())) return false;
      if (hasLastUsedAt() != other.hasLastUsedAt()) return false;
      if (hasLastUsedAt()) {
        if (!getLastUsedAt()
            .equals(other.getLastUsedAt())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + SERVICE_ACCOUNT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServiceAccountId().hashCode();
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + KEY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getKeyId().hashCode();
      if (hasLastUsedAt()) {
        hash = (37 * hash) + LAST_USED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getLastUsedAt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An access key.
     * For more information, see [AWS-compatible access keys](/docs/iam/concepts/authorization/access-key).
     * </pre>
     *
     * Protobuf type {@code yandex.cloud.iam.v1.awscompatibility.AccessKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yandex.cloud.iam.v1.awscompatibility.AccessKey)
        yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey.class, yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey.Builder.class);
      }

      // Construct using yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        serviceAccountId_ = "";

        if (createdAtBuilder_ == null) {
          createdAt_ = null;
        } else {
          createdAt_ = null;
          createdAtBuilder_ = null;
        }
        description_ = "";

        keyId_ = "";

        if (lastUsedAtBuilder_ == null) {
          lastUsedAt_ = null;
        } else {
          lastUsedAt_ = null;
          lastUsedAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_descriptor;
      }

      @java.lang.Override
      public yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey getDefaultInstanceForType() {
        return yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey.getDefaultInstance();
      }

      @java.lang.Override
      public yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey build() {
        yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey buildPartial() {
        yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey result = new yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey(this);
        result.id_ = id_;
        result.serviceAccountId_ = serviceAccountId_;
        if (createdAtBuilder_ == null) {
          result.createdAt_ = createdAt_;
        } else {
          result.createdAt_ = createdAtBuilder_.build();
        }
        result.description_ = description_;
        result.keyId_ = keyId_;
        if (lastUsedAtBuilder_ == null) {
          result.lastUsedAt_ = lastUsedAt_;
        } else {
          result.lastUsedAt_ = lastUsedAtBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey) {
          return mergeFrom((yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey other) {
        if (other == yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getServiceAccountId().isEmpty()) {
          serviceAccountId_ = other.serviceAccountId_;
          onChanged();
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getKeyId().isEmpty()) {
          keyId_ = other.keyId_;
          onChanged();
        }
        if (other.hasLastUsedAt()) {
          mergeLastUsedAt(other.getLastUsedAt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * ID of the AccessKey resource.
       * It is used to manage secret credentials: an access key ID and a secret access key.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ID of the AccessKey resource.
       * It is used to manage secret credentials: an access key ID and a secret access key.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ID of the AccessKey resource.
       * It is used to manage secret credentials: an access key ID and a secret access key.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the AccessKey resource.
       * It is used to manage secret credentials: an access key ID and a secret access key.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the AccessKey resource.
       * It is used to manage secret credentials: an access key ID and a secret access key.
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serviceAccountId_ = "";
      /**
       * <pre>
       * ID of the service account that the access key belongs to.
       * </pre>
       *
       * <code>string service_account_id = 2;</code>
       * @return The serviceAccountId.
       */
      public java.lang.String getServiceAccountId() {
        java.lang.Object ref = serviceAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ID of the service account that the access key belongs to.
       * </pre>
       *
       * <code>string service_account_id = 2;</code>
       * @return The bytes for serviceAccountId.
       */
      public com.google.protobuf.ByteString
          getServiceAccountIdBytes() {
        java.lang.Object ref = serviceAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ID of the service account that the access key belongs to.
       * </pre>
       *
       * <code>string service_account_id = 2;</code>
       * @param value The serviceAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setServiceAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the service account that the access key belongs to.
       * </pre>
       *
       * <code>string service_account_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceAccountId() {
        
        serviceAccountId_ = getDefaultInstance().getServiceAccountId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the service account that the access key belongs to.
       * </pre>
       *
       * <code>string service_account_id = 2;</code>
       * @param value The bytes for serviceAccountId to set.
       * @return This builder for chaining.
       */
      public Builder setServiceAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceAccountId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createdAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return createdAtBuilder_ != null || createdAt_ != null;
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       * @return The createdAt.
       */
      public com.google.protobuf.Timestamp getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
          onChanged();
        } else {
          createdAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
          onChanged();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (createdAt_ != null) {
            createdAt_ =
              com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
          } else {
            createdAt_ = value;
          }
          onChanged();
        } else {
          createdAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder clearCreatedAt() {
        if (createdAtBuilder_ == null) {
          createdAt_ = null;
          onChanged();
        } else {
          createdAt_ = null;
          createdAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
        
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <pre>
       * Creation timestamp.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }

      private java.lang.Object description_ = "";
      /**
       * <pre>
       * Description of the access key. 0-256 characters long.
       * </pre>
       *
       * <code>string description = 4;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Description of the access key. 0-256 characters long.
       * </pre>
       *
       * <code>string description = 4;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Description of the access key. 0-256 characters long.
       * </pre>
       *
       * <code>string description = 4;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Description of the access key. 0-256 characters long.
       * </pre>
       *
       * <code>string description = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Description of the access key. 0-256 characters long.
       * </pre>
       *
       * <code>string description = 4;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object keyId_ = "";
      /**
       * <pre>
       * ID of the access key.
       * The key is AWS compatible.
       * </pre>
       *
       * <code>string key_id = 5;</code>
       * @return The keyId.
       */
      public java.lang.String getKeyId() {
        java.lang.Object ref = keyId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * ID of the access key.
       * The key is AWS compatible.
       * </pre>
       *
       * <code>string key_id = 5;</code>
       * @return The bytes for keyId.
       */
      public com.google.protobuf.ByteString
          getKeyIdBytes() {
        java.lang.Object ref = keyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * ID of the access key.
       * The key is AWS compatible.
       * </pre>
       *
       * <code>string key_id = 5;</code>
       * @param value The keyId to set.
       * @return This builder for chaining.
       */
      public Builder setKeyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the access key.
       * The key is AWS compatible.
       * </pre>
       *
       * <code>string key_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyId() {
        
        keyId_ = getDefaultInstance().getKeyId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ID of the access key.
       * The key is AWS compatible.
       * </pre>
       *
       * <code>string key_id = 5;</code>
       * @param value The bytes for keyId to set.
       * @return This builder for chaining.
       */
      public Builder setKeyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp lastUsedAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUsedAtBuilder_;
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       * @return Whether the lastUsedAt field is set.
       */
      public boolean hasLastUsedAt() {
        return lastUsedAtBuilder_ != null || lastUsedAt_ != null;
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       * @return The lastUsedAt.
       */
      public com.google.protobuf.Timestamp getLastUsedAt() {
        if (lastUsedAtBuilder_ == null) {
          return lastUsedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUsedAt_;
        } else {
          return lastUsedAtBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       */
      public Builder setLastUsedAt(com.google.protobuf.Timestamp value) {
        if (lastUsedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastUsedAt_ = value;
          onChanged();
        } else {
          lastUsedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       */
      public Builder setLastUsedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (lastUsedAtBuilder_ == null) {
          lastUsedAt_ = builderForValue.build();
          onChanged();
        } else {
          lastUsedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       */
      public Builder mergeLastUsedAt(com.google.protobuf.Timestamp value) {
        if (lastUsedAtBuilder_ == null) {
          if (lastUsedAt_ != null) {
            lastUsedAt_ =
              com.google.protobuf.Timestamp.newBuilder(lastUsedAt_).mergeFrom(value).buildPartial();
          } else {
            lastUsedAt_ = value;
          }
          onChanged();
        } else {
          lastUsedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       */
      public Builder clearLastUsedAt() {
        if (lastUsedAtBuilder_ == null) {
          lastUsedAt_ = null;
          onChanged();
        } else {
          lastUsedAt_ = null;
          lastUsedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getLastUsedAtBuilder() {
        
        onChanged();
        return getLastUsedAtFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLastUsedAtOrBuilder() {
        if (lastUsedAtBuilder_ != null) {
          return lastUsedAtBuilder_.getMessageOrBuilder();
        } else {
          return lastUsedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : lastUsedAt_;
        }
      }
      /**
       * <pre>
       * Timestamp for the last authentication using this Access key.
       * </pre>
       *
       * <code>.google.protobuf.Timestamp last_used_at = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLastUsedAtFieldBuilder() {
        if (lastUsedAtBuilder_ == null) {
          lastUsedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLastUsedAt(),
                  getParentForChildren(),
                  isClean());
          lastUsedAt_ = null;
        }
        return lastUsedAtBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yandex.cloud.iam.v1.awscompatibility.AccessKey)
    }

    // @@protoc_insertion_point(class_scope:yandex.cloud.iam.v1.awscompatibility.AccessKey)
    private static final yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey();
    }

    public static yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccessKey>
        PARSER = new com.google.protobuf.AbstractParser<AccessKey>() {
      @java.lang.Override
      public AccessKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccessKey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccessKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccessKey> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yandex.cloud.api.iam.v1.awscompatibility.AccessKeyOuterClass.AccessKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5yandex/cloud/iam/v1/awscompatibility/a" +
      "ccess_key.proto\022$yandex.cloud.iam.v1.aws" +
      "compatibility\032\037google/protobuf/timestamp" +
      ".proto\"\300\001\n\tAccessKey\022\n\n\002id\030\001 \001(\t\022\032\n\022serv" +
      "ice_account_id\030\002 \001(\t\022.\n\ncreated_at\030\003 \001(\013" +
      "2\032.google.protobuf.Timestamp\022\023\n\013descript" +
      "ion\030\004 \001(\t\022\016\n\006key_id\030\005 \001(\t\0220\n\014last_used_a" +
      "t\030\007 \001(\0132\032.google.protobuf.TimestampJ\004\010\006\020" +
      "\007B\205\001\n(yandex.cloud.api.iam.v1.awscompati" +
      "bilityZYgithub.com/yandex-cloud/go-genpr" +
      "oto/yandex/cloud/iam/v1/awscompatibility" +
      ";awscompatibilityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_iam_v1_awscompatibility_AccessKey_descriptor,
        new java.lang.String[] { "Id", "ServiceAccountId", "CreatedAt", "Description", "KeyId", "LastUsedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
