// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yandex/cloud/cic/v1/common/lag_info.proto

package yandex.cloud.api.cic.v1.common;

public final class LagInfoOuterClass {
  private LagInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LagInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yandex.cloud.cic.v1.common.LagInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ID of LAG.
     * Optional.
     * If is not set scheduler selects it by himself.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value lag_id = 1;</code>
     * @return Whether the lagId field is set.
     */
    boolean hasLagId();
    /**
     * <pre>
     * ID of LAG.
     * Optional.
     * If is not set scheduler selects it by himself.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value lag_id = 1;</code>
     * @return The lagId.
     */
    com.google.protobuf.Int64Value getLagId();
    /**
     * <pre>
     * ID of LAG.
     * Optional.
     * If is not set scheduler selects it by himself.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value lag_id = 1;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getLagIdOrBuilder();

    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @return A list containing the portNames.
     */
    java.util.List<java.lang.String>
        getPortNamesList();
    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @return The count of portNames.
     */
    int getPortNamesCount();
    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @param index The index of the element to return.
     * @return The portNames at the given index.
     */
    java.lang.String getPortNames(int index);
    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the portNames at the given index.
     */
    com.google.protobuf.ByteString
        getPortNamesBytes(int index);
  }
  /**
   * Protobuf type {@code yandex.cloud.cic.v1.common.LagInfo}
   */
  public static final class LagInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yandex.cloud.cic.v1.common.LagInfo)
      LagInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LagInfo.newBuilder() to construct.
    private LagInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LagInfo() {
      portNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LagInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LagInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (lagId_ != null) {
                subBuilder = lagId_.toBuilder();
              }
              lagId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lagId_);
                lagId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                portNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              portNames_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          portNames_ = portNames_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yandex.cloud.api.cic.v1.common.LagInfoOuterClass.internal_static_yandex_cloud_cic_v1_common_LagInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yandex.cloud.api.cic.v1.common.LagInfoOuterClass.internal_static_yandex_cloud_cic_v1_common_LagInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo.class, yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo.Builder.class);
    }

    public static final int LAG_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.Int64Value lagId_;
    /**
     * <pre>
     * ID of LAG.
     * Optional.
     * If is not set scheduler selects it by himself.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value lag_id = 1;</code>
     * @return Whether the lagId field is set.
     */
    @java.lang.Override
    public boolean hasLagId() {
      return lagId_ != null;
    }
    /**
     * <pre>
     * ID of LAG.
     * Optional.
     * If is not set scheduler selects it by himself.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value lag_id = 1;</code>
     * @return The lagId.
     */
    @java.lang.Override
    public com.google.protobuf.Int64Value getLagId() {
      return lagId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : lagId_;
    }
    /**
     * <pre>
     * ID of LAG.
     * Optional.
     * If is not set scheduler selects it by himself.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value lag_id = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int64ValueOrBuilder getLagIdOrBuilder() {
      return getLagId();
    }

    public static final int PORT_NAMES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList portNames_;
    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @return A list containing the portNames.
     */
    public com.google.protobuf.ProtocolStringList
        getPortNamesList() {
      return portNames_;
    }
    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @return The count of portNames.
     */
    public int getPortNamesCount() {
      return portNames_.size();
    }
    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @param index The index of the element to return.
     * @return The portNames at the given index.
     */
    public java.lang.String getPortNames(int index) {
      return portNames_.get(index);
    }
    /**
     * <pre>
     * List of port names that the LAG is deployed on.
     * </pre>
     *
     * <code>repeated string port_names = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the portNames at the given index.
     */
    public com.google.protobuf.ByteString
        getPortNamesBytes(int index) {
      return portNames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lagId_ != null) {
        output.writeMessage(1, getLagId());
      }
      for (int i = 0; i < portNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, portNames_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lagId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLagId());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < portNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(portNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPortNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo)) {
        return super.equals(obj);
      }
      yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo other = (yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo) obj;

      if (hasLagId() != other.hasLagId()) return false;
      if (hasLagId()) {
        if (!getLagId()
            .equals(other.getLagId())) return false;
      }
      if (!getPortNamesList()
          .equals(other.getPortNamesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLagId()) {
        hash = (37 * hash) + LAG_ID_FIELD_NUMBER;
        hash = (53 * hash) + getLagId().hashCode();
      }
      if (getPortNamesCount() > 0) {
        hash = (37 * hash) + PORT_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getPortNamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yandex.cloud.cic.v1.common.LagInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yandex.cloud.cic.v1.common.LagInfo)
        yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.cic.v1.common.LagInfoOuterClass.internal_static_yandex_cloud_cic_v1_common_LagInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.cic.v1.common.LagInfoOuterClass.internal_static_yandex_cloud_cic_v1_common_LagInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo.class, yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo.Builder.class);
      }

      // Construct using yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (lagIdBuilder_ == null) {
          lagId_ = null;
        } else {
          lagId_ = null;
          lagIdBuilder_ = null;
        }
        portNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yandex.cloud.api.cic.v1.common.LagInfoOuterClass.internal_static_yandex_cloud_cic_v1_common_LagInfo_descriptor;
      }

      @java.lang.Override
      public yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo getDefaultInstanceForType() {
        return yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo.getDefaultInstance();
      }

      @java.lang.Override
      public yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo build() {
        yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo buildPartial() {
        yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo result = new yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo(this);
        int from_bitField0_ = bitField0_;
        if (lagIdBuilder_ == null) {
          result.lagId_ = lagId_;
        } else {
          result.lagId_ = lagIdBuilder_.build();
        }
        if (((bitField0_ & 0x00000001) != 0)) {
          portNames_ = portNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.portNames_ = portNames_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo) {
          return mergeFrom((yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo other) {
        if (other == yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo.getDefaultInstance()) return this;
        if (other.hasLagId()) {
          mergeLagId(other.getLagId());
        }
        if (!other.portNames_.isEmpty()) {
          if (portNames_.isEmpty()) {
            portNames_ = other.portNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePortNamesIsMutable();
            portNames_.addAll(other.portNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Int64Value lagId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> lagIdBuilder_;
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       * @return Whether the lagId field is set.
       */
      public boolean hasLagId() {
        return lagIdBuilder_ != null || lagId_ != null;
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       * @return The lagId.
       */
      public com.google.protobuf.Int64Value getLagId() {
        if (lagIdBuilder_ == null) {
          return lagId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : lagId_;
        } else {
          return lagIdBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       */
      public Builder setLagId(com.google.protobuf.Int64Value value) {
        if (lagIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lagId_ = value;
          onChanged();
        } else {
          lagIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       */
      public Builder setLagId(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (lagIdBuilder_ == null) {
          lagId_ = builderForValue.build();
          onChanged();
        } else {
          lagIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       */
      public Builder mergeLagId(com.google.protobuf.Int64Value value) {
        if (lagIdBuilder_ == null) {
          if (lagId_ != null) {
            lagId_ =
              com.google.protobuf.Int64Value.newBuilder(lagId_).mergeFrom(value).buildPartial();
          } else {
            lagId_ = value;
          }
          onChanged();
        } else {
          lagIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       */
      public Builder clearLagId() {
        if (lagIdBuilder_ == null) {
          lagId_ = null;
          onChanged();
        } else {
          lagId_ = null;
          lagIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       */
      public com.google.protobuf.Int64Value.Builder getLagIdBuilder() {
        
        onChanged();
        return getLagIdFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getLagIdOrBuilder() {
        if (lagIdBuilder_ != null) {
          return lagIdBuilder_.getMessageOrBuilder();
        } else {
          return lagId_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : lagId_;
        }
      }
      /**
       * <pre>
       * ID of LAG.
       * Optional.
       * If is not set scheduler selects it by himself.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value lag_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getLagIdFieldBuilder() {
        if (lagIdBuilder_ == null) {
          lagIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getLagId(),
                  getParentForChildren(),
                  isClean());
          lagId_ = null;
        }
        return lagIdBuilder_;
      }

      private com.google.protobuf.LazyStringList portNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePortNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          portNames_ = new com.google.protobuf.LazyStringArrayList(portNames_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @return A list containing the portNames.
       */
      public com.google.protobuf.ProtocolStringList
          getPortNamesList() {
        return portNames_.getUnmodifiableView();
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @return The count of portNames.
       */
      public int getPortNamesCount() {
        return portNames_.size();
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @param index The index of the element to return.
       * @return The portNames at the given index.
       */
      public java.lang.String getPortNames(int index) {
        return portNames_.get(index);
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the portNames at the given index.
       */
      public com.google.protobuf.ByteString
          getPortNamesBytes(int index) {
        return portNames_.getByteString(index);
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @param index The index to set the value at.
       * @param value The portNames to set.
       * @return This builder for chaining.
       */
      public Builder setPortNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePortNamesIsMutable();
        portNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @param value The portNames to add.
       * @return This builder for chaining.
       */
      public Builder addPortNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePortNamesIsMutable();
        portNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @param values The portNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllPortNames(
          java.lang.Iterable<java.lang.String> values) {
        ensurePortNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, portNames_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPortNames() {
        portNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of port names that the LAG is deployed on.
       * </pre>
       *
       * <code>repeated string port_names = 2;</code>
       * @param value The bytes of the portNames to add.
       * @return This builder for chaining.
       */
      public Builder addPortNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePortNamesIsMutable();
        portNames_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yandex.cloud.cic.v1.common.LagInfo)
    }

    // @@protoc_insertion_point(class_scope:yandex.cloud.cic.v1.common.LagInfo)
    private static final yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo();
    }

    public static yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LagInfo>
        PARSER = new com.google.protobuf.AbstractParser<LagInfo>() {
      @java.lang.Override
      public LagInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LagInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LagInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LagInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yandex.cloud.api.cic.v1.common.LagInfoOuterClass.LagInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_cic_v1_common_LagInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_cic_v1_common_LagInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)yandex/cloud/cic/v1/common/lag_info.pr" +
      "oto\022\032yandex.cloud.cic.v1.common\032\036google/" +
      "protobuf/wrappers.proto\"J\n\007LagInfo\022+\n\006la" +
      "g_id\030\001 \001(\0132\033.google.protobuf.Int64Value\022" +
      "\022\n\nport_names\030\002 \003(\tBd\n\036yandex.cloud.api." +
      "cic.v1.commonZBgithub.com/yandex-cloud/g" +
      "o-genproto/yandex/cloud/cic/v1/common;ci" +
      "cb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_yandex_cloud_cic_v1_common_LagInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yandex_cloud_cic_v1_common_LagInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_cic_v1_common_LagInfo_descriptor,
        new java.lang.String[] { "LagId", "PortNames", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
