// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yandex/cloud/mdb/redis/v1/config/redis6_0.proto

package yandex.cloud.api.mdb.redis.v1.config;

public final class Redis60 {
  private Redis60() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RedisConfig6_0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:yandex.cloud.mdb.redis.v1.config.RedisConfig6_0)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Redis key eviction policy for a dataset that reaches maximum memory,
     * available to the host. Redis maxmemory setting depends on Managed
     * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
     * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
     */
    int getMaxmemoryPolicyValue();
    /**
     * <pre>
     * Redis key eviction policy for a dataset that reaches maximum memory,
     * available to the host. Redis maxmemory setting depends on Managed
     * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
     * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
     */
    yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy getMaxmemoryPolicy();

    /**
     * <pre>
     * Time that Redis keeps the connection open while the client is idle.
     * If no new command is sent during that time, the connection is closed.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value timeout = 2;</code>
     */
    boolean hasTimeout();
    /**
     * <pre>
     * Time that Redis keeps the connection open while the client is idle.
     * If no new command is sent during that time, the connection is closed.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value timeout = 2;</code>
     */
    com.google.protobuf.Int64Value getTimeout();
    /**
     * <pre>
     * Time that Redis keeps the connection open while the client is idle.
     * If no new command is sent during that time, the connection is closed.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value timeout = 2;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getTimeoutOrBuilder();

    /**
     * <pre>
     * Authentication password.
     * </pre>
     *
     * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
     */
    java.lang.String getPassword();
    /**
     * <pre>
     * Authentication password.
     * </pre>
     *
     * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * <pre>
   * Fields and structure of `RedisConfig` reflects Redis configuration file
   * parameters.
   * </pre>
   *
   * Protobuf type {@code yandex.cloud.mdb.redis.v1.config.RedisConfig6_0}
   */
  public  static final class RedisConfig6_0 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yandex.cloud.mdb.redis.v1.config.RedisConfig6_0)
      RedisConfig6_0OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RedisConfig6_0.newBuilder() to construct.
    private RedisConfig6_0(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RedisConfig6_0() {
      maxmemoryPolicy_ = 0;
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RedisConfig6_0(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              maxmemoryPolicy_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (timeout_ != null) {
                subBuilder = timeout_.toBuilder();
              }
              timeout_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timeout_);
                timeout_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.class, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder.class);
    }

    /**
     * Protobuf enum {@code yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy}
     */
    public enum MaxmemoryPolicy
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MAXMEMORY_POLICY_UNSPECIFIED = 0;</code>
       */
      MAXMEMORY_POLICY_UNSPECIFIED(0),
      /**
       * <pre>
       * Try to remove less recently used (LRU) keys with `expire set`.
       * </pre>
       *
       * <code>VOLATILE_LRU = 1;</code>
       */
      VOLATILE_LRU(1),
      /**
       * <pre>
       * Remove less recently used (LRU) keys.
       * </pre>
       *
       * <code>ALLKEYS_LRU = 2;</code>
       */
      ALLKEYS_LRU(2),
      /**
       * <pre>
       * Try to remove least frequently used (LFU) keys with `expire set`.
       * </pre>
       *
       * <code>VOLATILE_LFU = 3;</code>
       */
      VOLATILE_LFU(3),
      /**
       * <pre>
       * Remove least frequently used (LFU) keys.
       * </pre>
       *
       * <code>ALLKEYS_LFU = 4;</code>
       */
      ALLKEYS_LFU(4),
      /**
       * <pre>
       * Try to remove keys with `expire set` randomly.
       * </pre>
       *
       * <code>VOLATILE_RANDOM = 5;</code>
       */
      VOLATILE_RANDOM(5),
      /**
       * <pre>
       * Remove keys randomly.
       * </pre>
       *
       * <code>ALLKEYS_RANDOM = 6;</code>
       */
      ALLKEYS_RANDOM(6),
      /**
       * <pre>
       * Try to remove less recently used (LRU) keys with `expire set`
       * and shorter TTL first.
       * </pre>
       *
       * <code>VOLATILE_TTL = 7;</code>
       */
      VOLATILE_TTL(7),
      /**
       * <pre>
       * Return errors when memory limit was reached and commands could require
       * more memory to be used.
       * </pre>
       *
       * <code>NOEVICTION = 8;</code>
       */
      NOEVICTION(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MAXMEMORY_POLICY_UNSPECIFIED = 0;</code>
       */
      public static final int MAXMEMORY_POLICY_UNSPECIFIED_VALUE = 0;
      /**
       * <pre>
       * Try to remove less recently used (LRU) keys with `expire set`.
       * </pre>
       *
       * <code>VOLATILE_LRU = 1;</code>
       */
      public static final int VOLATILE_LRU_VALUE = 1;
      /**
       * <pre>
       * Remove less recently used (LRU) keys.
       * </pre>
       *
       * <code>ALLKEYS_LRU = 2;</code>
       */
      public static final int ALLKEYS_LRU_VALUE = 2;
      /**
       * <pre>
       * Try to remove least frequently used (LFU) keys with `expire set`.
       * </pre>
       *
       * <code>VOLATILE_LFU = 3;</code>
       */
      public static final int VOLATILE_LFU_VALUE = 3;
      /**
       * <pre>
       * Remove least frequently used (LFU) keys.
       * </pre>
       *
       * <code>ALLKEYS_LFU = 4;</code>
       */
      public static final int ALLKEYS_LFU_VALUE = 4;
      /**
       * <pre>
       * Try to remove keys with `expire set` randomly.
       * </pre>
       *
       * <code>VOLATILE_RANDOM = 5;</code>
       */
      public static final int VOLATILE_RANDOM_VALUE = 5;
      /**
       * <pre>
       * Remove keys randomly.
       * </pre>
       *
       * <code>ALLKEYS_RANDOM = 6;</code>
       */
      public static final int ALLKEYS_RANDOM_VALUE = 6;
      /**
       * <pre>
       * Try to remove less recently used (LRU) keys with `expire set`
       * and shorter TTL first.
       * </pre>
       *
       * <code>VOLATILE_TTL = 7;</code>
       */
      public static final int VOLATILE_TTL_VALUE = 7;
      /**
       * <pre>
       * Return errors when memory limit was reached and commands could require
       * more memory to be used.
       * </pre>
       *
       * <code>NOEVICTION = 8;</code>
       */
      public static final int NOEVICTION_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MaxmemoryPolicy valueOf(int value) {
        return forNumber(value);
      }

      public static MaxmemoryPolicy forNumber(int value) {
        switch (value) {
          case 0: return MAXMEMORY_POLICY_UNSPECIFIED;
          case 1: return VOLATILE_LRU;
          case 2: return ALLKEYS_LRU;
          case 3: return VOLATILE_LFU;
          case 4: return ALLKEYS_LFU;
          case 5: return VOLATILE_RANDOM;
          case 6: return ALLKEYS_RANDOM;
          case 7: return VOLATILE_TTL;
          case 8: return NOEVICTION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MaxmemoryPolicy>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MaxmemoryPolicy> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MaxmemoryPolicy>() {
              public MaxmemoryPolicy findValueByNumber(int number) {
                return MaxmemoryPolicy.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDescriptor().getEnumTypes().get(0);
      }

      private static final MaxmemoryPolicy[] VALUES = values();

      public static MaxmemoryPolicy valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MaxmemoryPolicy(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy)
    }

    public static final int MAXMEMORY_POLICY_FIELD_NUMBER = 1;
    private int maxmemoryPolicy_;
    /**
     * <pre>
     * Redis key eviction policy for a dataset that reaches maximum memory,
     * available to the host. Redis maxmemory setting depends on Managed
     * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
     * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
     */
    public int getMaxmemoryPolicyValue() {
      return maxmemoryPolicy_;
    }
    /**
     * <pre>
     * Redis key eviction policy for a dataset that reaches maximum memory,
     * available to the host. Redis maxmemory setting depends on Managed
     * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
     * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
     */
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy getMaxmemoryPolicy() {
      @SuppressWarnings("deprecation")
      yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy result = yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy.valueOf(maxmemoryPolicy_);
      return result == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy.UNRECOGNIZED : result;
    }

    public static final int TIMEOUT_FIELD_NUMBER = 2;
    private com.google.protobuf.Int64Value timeout_;
    /**
     * <pre>
     * Time that Redis keeps the connection open while the client is idle.
     * If no new command is sent during that time, the connection is closed.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value timeout = 2;</code>
     */
    public boolean hasTimeout() {
      return timeout_ != null;
    }
    /**
     * <pre>
     * Time that Redis keeps the connection open while the client is idle.
     * If no new command is sent during that time, the connection is closed.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value timeout = 2;</code>
     */
    public com.google.protobuf.Int64Value getTimeout() {
      return timeout_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : timeout_;
    }
    /**
     * <pre>
     * Time that Redis keeps the connection open while the client is idle.
     * If no new command is sent during that time, the connection is closed.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value timeout = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getTimeoutOrBuilder() {
      return getTimeout();
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <pre>
     * Authentication password.
     * </pre>
     *
     * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Authentication password.
     * </pre>
     *
     * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (maxmemoryPolicy_ != yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy.MAXMEMORY_POLICY_UNSPECIFIED.getNumber()) {
        output.writeEnum(1, maxmemoryPolicy_);
      }
      if (timeout_ != null) {
        output.writeMessage(2, getTimeout());
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (maxmemoryPolicy_ != yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy.MAXMEMORY_POLICY_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, maxmemoryPolicy_);
      }
      if (timeout_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimeout());
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0)) {
        return super.equals(obj);
      }
      yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 other = (yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0) obj;

      boolean result = true;
      result = result && maxmemoryPolicy_ == other.maxmemoryPolicy_;
      result = result && (hasTimeout() == other.hasTimeout());
      if (hasTimeout()) {
        result = result && getTimeout()
            .equals(other.getTimeout());
      }
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAXMEMORY_POLICY_FIELD_NUMBER;
      hash = (53 * hash) + maxmemoryPolicy_;
      if (hasTimeout()) {
        hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
        hash = (53 * hash) + getTimeout().hashCode();
      }
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Fields and structure of `RedisConfig` reflects Redis configuration file
     * parameters.
     * </pre>
     *
     * Protobuf type {@code yandex.cloud.mdb.redis.v1.config.RedisConfig6_0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yandex.cloud.mdb.redis.v1.config.RedisConfig6_0)
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.class, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder.class);
      }

      // Construct using yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        maxmemoryPolicy_ = 0;

        if (timeoutBuilder_ == null) {
          timeout_ = null;
        } else {
          timeout_ = null;
          timeoutBuilder_ = null;
        }
        password_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_descriptor;
      }

      @java.lang.Override
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getDefaultInstanceForType() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance();
      }

      @java.lang.Override
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 build() {
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 buildPartial() {
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 result = new yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0(this);
        result.maxmemoryPolicy_ = maxmemoryPolicy_;
        if (timeoutBuilder_ == null) {
          result.timeout_ = timeout_;
        } else {
          result.timeout_ = timeoutBuilder_.build();
        }
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0) {
          return mergeFrom((yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 other) {
        if (other == yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance()) return this;
        if (other.maxmemoryPolicy_ != 0) {
          setMaxmemoryPolicyValue(other.getMaxmemoryPolicyValue());
        }
        if (other.hasTimeout()) {
          mergeTimeout(other.getTimeout());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int maxmemoryPolicy_ = 0;
      /**
       * <pre>
       * Redis key eviction policy for a dataset that reaches maximum memory,
       * available to the host. Redis maxmemory setting depends on Managed
       * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
       * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
       */
      public int getMaxmemoryPolicyValue() {
        return maxmemoryPolicy_;
      }
      /**
       * <pre>
       * Redis key eviction policy for a dataset that reaches maximum memory,
       * available to the host. Redis maxmemory setting depends on Managed
       * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
       * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
       */
      public Builder setMaxmemoryPolicyValue(int value) {
        maxmemoryPolicy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Redis key eviction policy for a dataset that reaches maximum memory,
       * available to the host. Redis maxmemory setting depends on Managed
       * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
       * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy getMaxmemoryPolicy() {
        @SuppressWarnings("deprecation")
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy result = yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy.valueOf(maxmemoryPolicy_);
        return result == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Redis key eviction policy for a dataset that reaches maximum memory,
       * available to the host. Redis maxmemory setting depends on Managed
       * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
       * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
       */
      public Builder setMaxmemoryPolicy(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.MaxmemoryPolicy value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        maxmemoryPolicy_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Redis key eviction policy for a dataset that reaches maximum memory,
       * available to the host. Redis maxmemory setting depends on Managed
       * Service for Redis [host class](/docs/managed-redis/concepts/instance-types).
       * All policies are described in detail in [Redis documentation](https://redis.io/topics/lru-cache).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0.MaxmemoryPolicy maxmemory_policy = 1;</code>
       */
      public Builder clearMaxmemoryPolicy() {
        
        maxmemoryPolicy_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Int64Value timeout_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> timeoutBuilder_;
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public boolean hasTimeout() {
        return timeoutBuilder_ != null || timeout_ != null;
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public com.google.protobuf.Int64Value getTimeout() {
        if (timeoutBuilder_ == null) {
          return timeout_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : timeout_;
        } else {
          return timeoutBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public Builder setTimeout(com.google.protobuf.Int64Value value) {
        if (timeoutBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timeout_ = value;
          onChanged();
        } else {
          timeoutBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public Builder setTimeout(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (timeoutBuilder_ == null) {
          timeout_ = builderForValue.build();
          onChanged();
        } else {
          timeoutBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public Builder mergeTimeout(com.google.protobuf.Int64Value value) {
        if (timeoutBuilder_ == null) {
          if (timeout_ != null) {
            timeout_ =
              com.google.protobuf.Int64Value.newBuilder(timeout_).mergeFrom(value).buildPartial();
          } else {
            timeout_ = value;
          }
          onChanged();
        } else {
          timeoutBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public Builder clearTimeout() {
        if (timeoutBuilder_ == null) {
          timeout_ = null;
          onChanged();
        } else {
          timeout_ = null;
          timeoutBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public com.google.protobuf.Int64Value.Builder getTimeoutBuilder() {
        
        onChanged();
        return getTimeoutFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getTimeoutOrBuilder() {
        if (timeoutBuilder_ != null) {
          return timeoutBuilder_.getMessageOrBuilder();
        } else {
          return timeout_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : timeout_;
        }
      }
      /**
       * <pre>
       * Time that Redis keeps the connection open while the client is idle.
       * If no new command is sent during that time, the connection is closed.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value timeout = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getTimeoutFieldBuilder() {
        if (timeoutBuilder_ == null) {
          timeoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getTimeout(),
                  getParentForChildren(),
                  isClean());
          timeout_ = null;
        }
        return timeoutBuilder_;
      }

      private java.lang.Object password_ = "";
      /**
       * <pre>
       * Authentication password.
       * </pre>
       *
       * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Authentication password.
       * </pre>
       *
       * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Authentication password.
       * </pre>
       *
       * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Authentication password.
       * </pre>
       *
       * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Authentication password.
       * </pre>
       *
       * <code>string password = 3 [(.yandex.cloud.pattern) = "[a-zA-Z0-9&#64;=+?*.,!&amp;#$^&lt;&gt;_-]{8,128}"];</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yandex.cloud.mdb.redis.v1.config.RedisConfig6_0)
    }

    // @@protoc_insertion_point(class_scope:yandex.cloud.mdb.redis.v1.config.RedisConfig6_0)
    private static final yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0();
    }

    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RedisConfig6_0>
        PARSER = new com.google.protobuf.AbstractParser<RedisConfig6_0>() {
      @java.lang.Override
      public RedisConfig6_0 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RedisConfig6_0(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RedisConfig6_0> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RedisConfig6_0> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RedisConfigSet6_0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:yandex.cloud.mdb.redis.v1.config.RedisConfigSet6_0)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Effective settings for a Redis 6.0 cluster (a combination of settings
     * defined in [user_config] and [default_config]).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
     */
    boolean hasEffectiveConfig();
    /**
     * <pre>
     * Effective settings for a Redis 6.0 cluster (a combination of settings
     * defined in [user_config] and [default_config]).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
     */
    yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getEffectiveConfig();
    /**
     * <pre>
     * Effective settings for a Redis 6.0 cluster (a combination of settings
     * defined in [user_config] and [default_config]).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
     */
    yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getEffectiveConfigOrBuilder();

    /**
     * <pre>
     * User-defined settings for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
     */
    boolean hasUserConfig();
    /**
     * <pre>
     * User-defined settings for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
     */
    yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getUserConfig();
    /**
     * <pre>
     * User-defined settings for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
     */
    yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getUserConfigOrBuilder();

    /**
     * <pre>
     * Default configuration for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
     */
    boolean hasDefaultConfig();
    /**
     * <pre>
     * Default configuration for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
     */
    yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getDefaultConfig();
    /**
     * <pre>
     * Default configuration for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
     */
    yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getDefaultConfigOrBuilder();
  }
  /**
   * Protobuf type {@code yandex.cloud.mdb.redis.v1.config.RedisConfigSet6_0}
   */
  public  static final class RedisConfigSet6_0 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yandex.cloud.mdb.redis.v1.config.RedisConfigSet6_0)
      RedisConfigSet6_0OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RedisConfigSet6_0.newBuilder() to construct.
    private RedisConfigSet6_0(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RedisConfigSet6_0() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RedisConfigSet6_0(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder subBuilder = null;
              if (effectiveConfig_ != null) {
                subBuilder = effectiveConfig_.toBuilder();
              }
              effectiveConfig_ = input.readMessage(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(effectiveConfig_);
                effectiveConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder subBuilder = null;
              if (userConfig_ != null) {
                subBuilder = userConfig_.toBuilder();
              }
              userConfig_ = input.readMessage(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userConfig_);
                userConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder subBuilder = null;
              if (defaultConfig_ != null) {
                subBuilder = defaultConfig_.toBuilder();
              }
              defaultConfig_ = input.readMessage(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(defaultConfig_);
                defaultConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0.class, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0.Builder.class);
    }

    public static final int EFFECTIVE_CONFIG_FIELD_NUMBER = 1;
    private yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 effectiveConfig_;
    /**
     * <pre>
     * Effective settings for a Redis 6.0 cluster (a combination of settings
     * defined in [user_config] and [default_config]).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
     */
    public boolean hasEffectiveConfig() {
      return effectiveConfig_ != null;
    }
    /**
     * <pre>
     * Effective settings for a Redis 6.0 cluster (a combination of settings
     * defined in [user_config] and [default_config]).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
     */
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getEffectiveConfig() {
      return effectiveConfig_ == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : effectiveConfig_;
    }
    /**
     * <pre>
     * Effective settings for a Redis 6.0 cluster (a combination of settings
     * defined in [user_config] and [default_config]).
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
     */
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getEffectiveConfigOrBuilder() {
      return getEffectiveConfig();
    }

    public static final int USER_CONFIG_FIELD_NUMBER = 2;
    private yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 userConfig_;
    /**
     * <pre>
     * User-defined settings for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
     */
    public boolean hasUserConfig() {
      return userConfig_ != null;
    }
    /**
     * <pre>
     * User-defined settings for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
     */
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getUserConfig() {
      return userConfig_ == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : userConfig_;
    }
    /**
     * <pre>
     * User-defined settings for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
     */
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getUserConfigOrBuilder() {
      return getUserConfig();
    }

    public static final int DEFAULT_CONFIG_FIELD_NUMBER = 3;
    private yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 defaultConfig_;
    /**
     * <pre>
     * Default configuration for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
     */
    public boolean hasDefaultConfig() {
      return defaultConfig_ != null;
    }
    /**
     * <pre>
     * Default configuration for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
     */
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getDefaultConfig() {
      return defaultConfig_ == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : defaultConfig_;
    }
    /**
     * <pre>
     * Default configuration for a Redis 6.0 cluster.
     * </pre>
     *
     * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
     */
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getDefaultConfigOrBuilder() {
      return getDefaultConfig();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (effectiveConfig_ != null) {
        output.writeMessage(1, getEffectiveConfig());
      }
      if (userConfig_ != null) {
        output.writeMessage(2, getUserConfig());
      }
      if (defaultConfig_ != null) {
        output.writeMessage(3, getDefaultConfig());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (effectiveConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEffectiveConfig());
      }
      if (userConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUserConfig());
      }
      if (defaultConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDefaultConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0)) {
        return super.equals(obj);
      }
      yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 other = (yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0) obj;

      boolean result = true;
      result = result && (hasEffectiveConfig() == other.hasEffectiveConfig());
      if (hasEffectiveConfig()) {
        result = result && getEffectiveConfig()
            .equals(other.getEffectiveConfig());
      }
      result = result && (hasUserConfig() == other.hasUserConfig());
      if (hasUserConfig()) {
        result = result && getUserConfig()
            .equals(other.getUserConfig());
      }
      result = result && (hasDefaultConfig() == other.hasDefaultConfig());
      if (hasDefaultConfig()) {
        result = result && getDefaultConfig()
            .equals(other.getDefaultConfig());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEffectiveConfig()) {
        hash = (37 * hash) + EFFECTIVE_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getEffectiveConfig().hashCode();
      }
      if (hasUserConfig()) {
        hash = (37 * hash) + USER_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getUserConfig().hashCode();
      }
      if (hasDefaultConfig()) {
        hash = (37 * hash) + DEFAULT_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getDefaultConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yandex.cloud.mdb.redis.v1.config.RedisConfigSet6_0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yandex.cloud.mdb.redis.v1.config.RedisConfigSet6_0)
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0.class, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0.Builder.class);
      }

      // Construct using yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (effectiveConfigBuilder_ == null) {
          effectiveConfig_ = null;
        } else {
          effectiveConfig_ = null;
          effectiveConfigBuilder_ = null;
        }
        if (userConfigBuilder_ == null) {
          userConfig_ = null;
        } else {
          userConfig_ = null;
          userConfigBuilder_ = null;
        }
        if (defaultConfigBuilder_ == null) {
          defaultConfig_ = null;
        } else {
          defaultConfig_ = null;
          defaultConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_descriptor;
      }

      @java.lang.Override
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 getDefaultInstanceForType() {
        return yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0.getDefaultInstance();
      }

      @java.lang.Override
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 build() {
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 buildPartial() {
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 result = new yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0(this);
        if (effectiveConfigBuilder_ == null) {
          result.effectiveConfig_ = effectiveConfig_;
        } else {
          result.effectiveConfig_ = effectiveConfigBuilder_.build();
        }
        if (userConfigBuilder_ == null) {
          result.userConfig_ = userConfig_;
        } else {
          result.userConfig_ = userConfigBuilder_.build();
        }
        if (defaultConfigBuilder_ == null) {
          result.defaultConfig_ = defaultConfig_;
        } else {
          result.defaultConfig_ = defaultConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0) {
          return mergeFrom((yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 other) {
        if (other == yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0.getDefaultInstance()) return this;
        if (other.hasEffectiveConfig()) {
          mergeEffectiveConfig(other.getEffectiveConfig());
        }
        if (other.hasUserConfig()) {
          mergeUserConfig(other.getUserConfig());
        }
        if (other.hasDefaultConfig()) {
          mergeDefaultConfig(other.getDefaultConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 effectiveConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder> effectiveConfigBuilder_;
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public boolean hasEffectiveConfig() {
        return effectiveConfigBuilder_ != null || effectiveConfig_ != null;
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getEffectiveConfig() {
        if (effectiveConfigBuilder_ == null) {
          return effectiveConfig_ == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : effectiveConfig_;
        } else {
          return effectiveConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public Builder setEffectiveConfig(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 value) {
        if (effectiveConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          effectiveConfig_ = value;
          onChanged();
        } else {
          effectiveConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public Builder setEffectiveConfig(
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder builderForValue) {
        if (effectiveConfigBuilder_ == null) {
          effectiveConfig_ = builderForValue.build();
          onChanged();
        } else {
          effectiveConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public Builder mergeEffectiveConfig(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 value) {
        if (effectiveConfigBuilder_ == null) {
          if (effectiveConfig_ != null) {
            effectiveConfig_ =
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.newBuilder(effectiveConfig_).mergeFrom(value).buildPartial();
          } else {
            effectiveConfig_ = value;
          }
          onChanged();
        } else {
          effectiveConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public Builder clearEffectiveConfig() {
        if (effectiveConfigBuilder_ == null) {
          effectiveConfig_ = null;
          onChanged();
        } else {
          effectiveConfig_ = null;
          effectiveConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder getEffectiveConfigBuilder() {
        
        onChanged();
        return getEffectiveConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getEffectiveConfigOrBuilder() {
        if (effectiveConfigBuilder_ != null) {
          return effectiveConfigBuilder_.getMessageOrBuilder();
        } else {
          return effectiveConfig_ == null ?
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : effectiveConfig_;
        }
      }
      /**
       * <pre>
       * Effective settings for a Redis 6.0 cluster (a combination of settings
       * defined in [user_config] and [default_config]).
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 effective_config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder> 
          getEffectiveConfigFieldBuilder() {
        if (effectiveConfigBuilder_ == null) {
          effectiveConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder>(
                  getEffectiveConfig(),
                  getParentForChildren(),
                  isClean());
          effectiveConfig_ = null;
        }
        return effectiveConfigBuilder_;
      }

      private yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 userConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder> userConfigBuilder_;
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public boolean hasUserConfig() {
        return userConfigBuilder_ != null || userConfig_ != null;
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getUserConfig() {
        if (userConfigBuilder_ == null) {
          return userConfig_ == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : userConfig_;
        } else {
          return userConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public Builder setUserConfig(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 value) {
        if (userConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userConfig_ = value;
          onChanged();
        } else {
          userConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public Builder setUserConfig(
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder builderForValue) {
        if (userConfigBuilder_ == null) {
          userConfig_ = builderForValue.build();
          onChanged();
        } else {
          userConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public Builder mergeUserConfig(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 value) {
        if (userConfigBuilder_ == null) {
          if (userConfig_ != null) {
            userConfig_ =
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.newBuilder(userConfig_).mergeFrom(value).buildPartial();
          } else {
            userConfig_ = value;
          }
          onChanged();
        } else {
          userConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public Builder clearUserConfig() {
        if (userConfigBuilder_ == null) {
          userConfig_ = null;
          onChanged();
        } else {
          userConfig_ = null;
          userConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder getUserConfigBuilder() {
        
        onChanged();
        return getUserConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getUserConfigOrBuilder() {
        if (userConfigBuilder_ != null) {
          return userConfigBuilder_.getMessageOrBuilder();
        } else {
          return userConfig_ == null ?
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : userConfig_;
        }
      }
      /**
       * <pre>
       * User-defined settings for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 user_config = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder> 
          getUserConfigFieldBuilder() {
        if (userConfigBuilder_ == null) {
          userConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder>(
                  getUserConfig(),
                  getParentForChildren(),
                  isClean());
          userConfig_ = null;
        }
        return userConfigBuilder_;
      }

      private yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 defaultConfig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder> defaultConfigBuilder_;
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public boolean hasDefaultConfig() {
        return defaultConfigBuilder_ != null || defaultConfig_ != null;
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 getDefaultConfig() {
        if (defaultConfigBuilder_ == null) {
          return defaultConfig_ == null ? yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : defaultConfig_;
        } else {
          return defaultConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public Builder setDefaultConfig(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 value) {
        if (defaultConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          defaultConfig_ = value;
          onChanged();
        } else {
          defaultConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public Builder setDefaultConfig(
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder builderForValue) {
        if (defaultConfigBuilder_ == null) {
          defaultConfig_ = builderForValue.build();
          onChanged();
        } else {
          defaultConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public Builder mergeDefaultConfig(yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0 value) {
        if (defaultConfigBuilder_ == null) {
          if (defaultConfig_ != null) {
            defaultConfig_ =
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.newBuilder(defaultConfig_).mergeFrom(value).buildPartial();
          } else {
            defaultConfig_ = value;
          }
          onChanged();
        } else {
          defaultConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public Builder clearDefaultConfig() {
        if (defaultConfigBuilder_ == null) {
          defaultConfig_ = null;
          onChanged();
        } else {
          defaultConfig_ = null;
          defaultConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder getDefaultConfigBuilder() {
        
        onChanged();
        return getDefaultConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder getDefaultConfigOrBuilder() {
        if (defaultConfigBuilder_ != null) {
          return defaultConfigBuilder_.getMessageOrBuilder();
        } else {
          return defaultConfig_ == null ?
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.getDefaultInstance() : defaultConfig_;
        }
      }
      /**
       * <pre>
       * Default configuration for a Redis 6.0 cluster.
       * </pre>
       *
       * <code>.yandex.cloud.mdb.redis.v1.config.RedisConfig6_0 default_config = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder> 
          getDefaultConfigFieldBuilder() {
        if (defaultConfigBuilder_ == null) {
          defaultConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0.Builder, yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfig6_0OrBuilder>(
                  getDefaultConfig(),
                  getParentForChildren(),
                  isClean());
          defaultConfig_ = null;
        }
        return defaultConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yandex.cloud.mdb.redis.v1.config.RedisConfigSet6_0)
    }

    // @@protoc_insertion_point(class_scope:yandex.cloud.mdb.redis.v1.config.RedisConfigSet6_0)
    private static final yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0();
    }

    public static yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RedisConfigSet6_0>
        PARSER = new com.google.protobuf.AbstractParser<RedisConfigSet6_0>() {
      @java.lang.Override
      public RedisConfigSet6_0 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RedisConfigSet6_0(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RedisConfigSet6_0> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RedisConfigSet6_0> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yandex.cloud.api.mdb.redis.v1.config.Redis60.RedisConfigSet6_0 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/yandex/cloud/mdb/redis/v1/config/redis" +
      "6_0.proto\022 yandex.cloud.mdb.redis.v1.con" +
      "fig\032\036google/protobuf/wrappers.proto\032\035yan" +
      "dex/cloud/validation.proto\"\233\003\n\016RedisConf" +
      "ig6_0\022Z\n\020maxmemory_policy\030\001 \001(\0162@.yandex" +
      ".cloud.mdb.redis.v1.config.RedisConfig6_" +
      "0.MaxmemoryPolicy\022,\n\007timeout\030\002 \001(\0132\033.goo" +
      "gle.protobuf.Int64Value\0228\n\010password\030\003 \001(" +
      "\tB&\362\3071\"[a-zA-Z0-9@=+?*.,!&#$^<>_-]{8,128" +
      "}\"\304\001\n\017MaxmemoryPolicy\022 \n\034MAXMEMORY_POLIC" +
      "Y_UNSPECIFIED\020\000\022\020\n\014VOLATILE_LRU\020\001\022\017\n\013ALL" +
      "KEYS_LRU\020\002\022\020\n\014VOLATILE_LFU\020\003\022\017\n\013ALLKEYS_" +
      "LFU\020\004\022\023\n\017VOLATILE_RANDOM\020\005\022\022\n\016ALLKEYS_RA" +
      "NDOM\020\006\022\020\n\014VOLATILE_TTL\020\007\022\016\n\nNOEVICTION\020\010" +
      "\"\360\001\n\021RedisConfigSet6_0\022J\n\020effective_conf" +
      "ig\030\001 \001(\01320.yandex.cloud.mdb.redis.v1.con" +
      "fig.RedisConfig6_0\022E\n\013user_config\030\002 \001(\0132" +
      "0.yandex.cloud.mdb.redis.v1.config.Redis" +
      "Config6_0\022H\n\016default_config\030\003 \001(\01320.yand" +
      "ex.cloud.mdb.redis.v1.config.RedisConfig" +
      "6_0Br\n$yandex.cloud.api.mdb.redis.v1.con" +
      "figZJgithub.com/yandex-cloud/go-genproto" +
      "/yandex/cloud/mdb/redis/v1/config;redisb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          yandex.cloud.api.Validation.getDescriptor(),
        }, assigner);
    internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfig6_0_descriptor,
        new java.lang.String[] { "MaxmemoryPolicy", "Timeout", "Password", });
    internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_mdb_redis_v1_config_RedisConfigSet6_0_descriptor,
        new java.lang.String[] { "EffectiveConfig", "UserConfig", "DefaultConfig", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(yandex.cloud.api.Validation.pattern);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.WrappersProto.getDescriptor();
    yandex.cloud.api.Validation.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
