// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yandex/cloud/loadtesting/api/v1/common/quantiles.proto

package yandex.cloud.api.loadtesting.api.v1.common;

public final class QuantilesOuterClass {
  private QuantilesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuantilesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yandex.cloud.loadtesting.api.v1.common.Quantiles)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 50 percentile (median).
     * </pre>
     *
     * <code>double q50 = 1;</code>
     * @return The q50.
     */
    double getQ50();

    /**
     * <pre>
     * 75 percentile.
     * </pre>
     *
     * <code>double q75 = 2;</code>
     * @return The q75.
     */
    double getQ75();

    /**
     * <pre>
     * 80 percentile.
     * </pre>
     *
     * <code>double q80 = 3;</code>
     * @return The q80.
     */
    double getQ80();

    /**
     * <pre>
     * 85 percentile.
     * </pre>
     *
     * <code>double q85 = 4;</code>
     * @return The q85.
     */
    double getQ85();

    /**
     * <pre>
     * 90 percentile.
     * </pre>
     *
     * <code>double q90 = 5;</code>
     * @return The q90.
     */
    double getQ90();

    /**
     * <pre>
     * 95 percentile.
     * </pre>
     *
     * <code>double q95 = 6;</code>
     * @return The q95.
     */
    double getQ95();

    /**
     * <pre>
     * 98 percentile.
     * </pre>
     *
     * <code>double q98 = 7;</code>
     * @return The q98.
     */
    double getQ98();

    /**
     * <pre>
     * 99 percentile.
     * </pre>
     *
     * <code>double q99 = 8;</code>
     * @return The q99.
     */
    double getQ99();

    /**
     * <pre>
     * 100 percentile (maximum or minimum).
     * </pre>
     *
     * <code>double q100 = 9;</code>
     * @return The q100.
     */
    double getQ100();
  }
  /**
   * <pre>
   * Statistical data aggregated by predefined set of quantiles.
   * </pre>
   *
   * Protobuf type {@code yandex.cloud.loadtesting.api.v1.common.Quantiles}
   */
  public static final class Quantiles extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yandex.cloud.loadtesting.api.v1.common.Quantiles)
      QuantilesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Quantiles.newBuilder() to construct.
    private Quantiles(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Quantiles() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Quantiles();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Quantiles(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              q50_ = input.readDouble();
              break;
            }
            case 17: {

              q75_ = input.readDouble();
              break;
            }
            case 25: {

              q80_ = input.readDouble();
              break;
            }
            case 33: {

              q85_ = input.readDouble();
              break;
            }
            case 41: {

              q90_ = input.readDouble();
              break;
            }
            case 49: {

              q95_ = input.readDouble();
              break;
            }
            case 57: {

              q98_ = input.readDouble();
              break;
            }
            case 65: {

              q99_ = input.readDouble();
              break;
            }
            case 73: {

              q100_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles.class, yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles.Builder.class);
    }

    public static final int Q50_FIELD_NUMBER = 1;
    private double q50_;
    /**
     * <pre>
     * 50 percentile (median).
     * </pre>
     *
     * <code>double q50 = 1;</code>
     * @return The q50.
     */
    @java.lang.Override
    public double getQ50() {
      return q50_;
    }

    public static final int Q75_FIELD_NUMBER = 2;
    private double q75_;
    /**
     * <pre>
     * 75 percentile.
     * </pre>
     *
     * <code>double q75 = 2;</code>
     * @return The q75.
     */
    @java.lang.Override
    public double getQ75() {
      return q75_;
    }

    public static final int Q80_FIELD_NUMBER = 3;
    private double q80_;
    /**
     * <pre>
     * 80 percentile.
     * </pre>
     *
     * <code>double q80 = 3;</code>
     * @return The q80.
     */
    @java.lang.Override
    public double getQ80() {
      return q80_;
    }

    public static final int Q85_FIELD_NUMBER = 4;
    private double q85_;
    /**
     * <pre>
     * 85 percentile.
     * </pre>
     *
     * <code>double q85 = 4;</code>
     * @return The q85.
     */
    @java.lang.Override
    public double getQ85() {
      return q85_;
    }

    public static final int Q90_FIELD_NUMBER = 5;
    private double q90_;
    /**
     * <pre>
     * 90 percentile.
     * </pre>
     *
     * <code>double q90 = 5;</code>
     * @return The q90.
     */
    @java.lang.Override
    public double getQ90() {
      return q90_;
    }

    public static final int Q95_FIELD_NUMBER = 6;
    private double q95_;
    /**
     * <pre>
     * 95 percentile.
     * </pre>
     *
     * <code>double q95 = 6;</code>
     * @return The q95.
     */
    @java.lang.Override
    public double getQ95() {
      return q95_;
    }

    public static final int Q98_FIELD_NUMBER = 7;
    private double q98_;
    /**
     * <pre>
     * 98 percentile.
     * </pre>
     *
     * <code>double q98 = 7;</code>
     * @return The q98.
     */
    @java.lang.Override
    public double getQ98() {
      return q98_;
    }

    public static final int Q99_FIELD_NUMBER = 8;
    private double q99_;
    /**
     * <pre>
     * 99 percentile.
     * </pre>
     *
     * <code>double q99 = 8;</code>
     * @return The q99.
     */
    @java.lang.Override
    public double getQ99() {
      return q99_;
    }

    public static final int Q100_FIELD_NUMBER = 9;
    private double q100_;
    /**
     * <pre>
     * 100 percentile (maximum or minimum).
     * </pre>
     *
     * <code>double q100 = 9;</code>
     * @return The q100.
     */
    @java.lang.Override
    public double getQ100() {
      return q100_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(q50_) != 0) {
        output.writeDouble(1, q50_);
      }
      if (java.lang.Double.doubleToRawLongBits(q75_) != 0) {
        output.writeDouble(2, q75_);
      }
      if (java.lang.Double.doubleToRawLongBits(q80_) != 0) {
        output.writeDouble(3, q80_);
      }
      if (java.lang.Double.doubleToRawLongBits(q85_) != 0) {
        output.writeDouble(4, q85_);
      }
      if (java.lang.Double.doubleToRawLongBits(q90_) != 0) {
        output.writeDouble(5, q90_);
      }
      if (java.lang.Double.doubleToRawLongBits(q95_) != 0) {
        output.writeDouble(6, q95_);
      }
      if (java.lang.Double.doubleToRawLongBits(q98_) != 0) {
        output.writeDouble(7, q98_);
      }
      if (java.lang.Double.doubleToRawLongBits(q99_) != 0) {
        output.writeDouble(8, q99_);
      }
      if (java.lang.Double.doubleToRawLongBits(q100_) != 0) {
        output.writeDouble(9, q100_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(q50_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, q50_);
      }
      if (java.lang.Double.doubleToRawLongBits(q75_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, q75_);
      }
      if (java.lang.Double.doubleToRawLongBits(q80_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, q80_);
      }
      if (java.lang.Double.doubleToRawLongBits(q85_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, q85_);
      }
      if (java.lang.Double.doubleToRawLongBits(q90_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, q90_);
      }
      if (java.lang.Double.doubleToRawLongBits(q95_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, q95_);
      }
      if (java.lang.Double.doubleToRawLongBits(q98_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, q98_);
      }
      if (java.lang.Double.doubleToRawLongBits(q99_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, q99_);
      }
      if (java.lang.Double.doubleToRawLongBits(q100_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, q100_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles)) {
        return super.equals(obj);
      }
      yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles other = (yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles) obj;

      if (java.lang.Double.doubleToLongBits(getQ50())
          != java.lang.Double.doubleToLongBits(
              other.getQ50())) return false;
      if (java.lang.Double.doubleToLongBits(getQ75())
          != java.lang.Double.doubleToLongBits(
              other.getQ75())) return false;
      if (java.lang.Double.doubleToLongBits(getQ80())
          != java.lang.Double.doubleToLongBits(
              other.getQ80())) return false;
      if (java.lang.Double.doubleToLongBits(getQ85())
          != java.lang.Double.doubleToLongBits(
              other.getQ85())) return false;
      if (java.lang.Double.doubleToLongBits(getQ90())
          != java.lang.Double.doubleToLongBits(
              other.getQ90())) return false;
      if (java.lang.Double.doubleToLongBits(getQ95())
          != java.lang.Double.doubleToLongBits(
              other.getQ95())) return false;
      if (java.lang.Double.doubleToLongBits(getQ98())
          != java.lang.Double.doubleToLongBits(
              other.getQ98())) return false;
      if (java.lang.Double.doubleToLongBits(getQ99())
          != java.lang.Double.doubleToLongBits(
              other.getQ99())) return false;
      if (java.lang.Double.doubleToLongBits(getQ100())
          != java.lang.Double.doubleToLongBits(
              other.getQ100())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + Q50_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ50()));
      hash = (37 * hash) + Q75_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ75()));
      hash = (37 * hash) + Q80_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ80()));
      hash = (37 * hash) + Q85_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ85()));
      hash = (37 * hash) + Q90_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ90()));
      hash = (37 * hash) + Q95_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ95()));
      hash = (37 * hash) + Q98_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ98()));
      hash = (37 * hash) + Q99_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ99()));
      hash = (37 * hash) + Q100_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQ100()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Statistical data aggregated by predefined set of quantiles.
     * </pre>
     *
     * Protobuf type {@code yandex.cloud.loadtesting.api.v1.common.Quantiles}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yandex.cloud.loadtesting.api.v1.common.Quantiles)
        yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.QuantilesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles.class, yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles.Builder.class);
      }

      // Construct using yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        q50_ = 0D;

        q75_ = 0D;

        q80_ = 0D;

        q85_ = 0D;

        q90_ = 0D;

        q95_ = 0D;

        q98_ = 0D;

        q99_ = 0D;

        q100_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_descriptor;
      }

      @java.lang.Override
      public yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles getDefaultInstanceForType() {
        return yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles.getDefaultInstance();
      }

      @java.lang.Override
      public yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles build() {
        yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles buildPartial() {
        yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles result = new yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles(this);
        result.q50_ = q50_;
        result.q75_ = q75_;
        result.q80_ = q80_;
        result.q85_ = q85_;
        result.q90_ = q90_;
        result.q95_ = q95_;
        result.q98_ = q98_;
        result.q99_ = q99_;
        result.q100_ = q100_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles) {
          return mergeFrom((yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles other) {
        if (other == yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles.getDefaultInstance()) return this;
        if (other.getQ50() != 0D) {
          setQ50(other.getQ50());
        }
        if (other.getQ75() != 0D) {
          setQ75(other.getQ75());
        }
        if (other.getQ80() != 0D) {
          setQ80(other.getQ80());
        }
        if (other.getQ85() != 0D) {
          setQ85(other.getQ85());
        }
        if (other.getQ90() != 0D) {
          setQ90(other.getQ90());
        }
        if (other.getQ95() != 0D) {
          setQ95(other.getQ95());
        }
        if (other.getQ98() != 0D) {
          setQ98(other.getQ98());
        }
        if (other.getQ99() != 0D) {
          setQ99(other.getQ99());
        }
        if (other.getQ100() != 0D) {
          setQ100(other.getQ100());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double q50_ ;
      /**
       * <pre>
       * 50 percentile (median).
       * </pre>
       *
       * <code>double q50 = 1;</code>
       * @return The q50.
       */
      @java.lang.Override
      public double getQ50() {
        return q50_;
      }
      /**
       * <pre>
       * 50 percentile (median).
       * </pre>
       *
       * <code>double q50 = 1;</code>
       * @param value The q50 to set.
       * @return This builder for chaining.
       */
      public Builder setQ50(double value) {
        
        q50_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 50 percentile (median).
       * </pre>
       *
       * <code>double q50 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ50() {
        
        q50_ = 0D;
        onChanged();
        return this;
      }

      private double q75_ ;
      /**
       * <pre>
       * 75 percentile.
       * </pre>
       *
       * <code>double q75 = 2;</code>
       * @return The q75.
       */
      @java.lang.Override
      public double getQ75() {
        return q75_;
      }
      /**
       * <pre>
       * 75 percentile.
       * </pre>
       *
       * <code>double q75 = 2;</code>
       * @param value The q75 to set.
       * @return This builder for chaining.
       */
      public Builder setQ75(double value) {
        
        q75_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 75 percentile.
       * </pre>
       *
       * <code>double q75 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ75() {
        
        q75_ = 0D;
        onChanged();
        return this;
      }

      private double q80_ ;
      /**
       * <pre>
       * 80 percentile.
       * </pre>
       *
       * <code>double q80 = 3;</code>
       * @return The q80.
       */
      @java.lang.Override
      public double getQ80() {
        return q80_;
      }
      /**
       * <pre>
       * 80 percentile.
       * </pre>
       *
       * <code>double q80 = 3;</code>
       * @param value The q80 to set.
       * @return This builder for chaining.
       */
      public Builder setQ80(double value) {
        
        q80_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 80 percentile.
       * </pre>
       *
       * <code>double q80 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ80() {
        
        q80_ = 0D;
        onChanged();
        return this;
      }

      private double q85_ ;
      /**
       * <pre>
       * 85 percentile.
       * </pre>
       *
       * <code>double q85 = 4;</code>
       * @return The q85.
       */
      @java.lang.Override
      public double getQ85() {
        return q85_;
      }
      /**
       * <pre>
       * 85 percentile.
       * </pre>
       *
       * <code>double q85 = 4;</code>
       * @param value The q85 to set.
       * @return This builder for chaining.
       */
      public Builder setQ85(double value) {
        
        q85_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 85 percentile.
       * </pre>
       *
       * <code>double q85 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ85() {
        
        q85_ = 0D;
        onChanged();
        return this;
      }

      private double q90_ ;
      /**
       * <pre>
       * 90 percentile.
       * </pre>
       *
       * <code>double q90 = 5;</code>
       * @return The q90.
       */
      @java.lang.Override
      public double getQ90() {
        return q90_;
      }
      /**
       * <pre>
       * 90 percentile.
       * </pre>
       *
       * <code>double q90 = 5;</code>
       * @param value The q90 to set.
       * @return This builder for chaining.
       */
      public Builder setQ90(double value) {
        
        q90_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 90 percentile.
       * </pre>
       *
       * <code>double q90 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ90() {
        
        q90_ = 0D;
        onChanged();
        return this;
      }

      private double q95_ ;
      /**
       * <pre>
       * 95 percentile.
       * </pre>
       *
       * <code>double q95 = 6;</code>
       * @return The q95.
       */
      @java.lang.Override
      public double getQ95() {
        return q95_;
      }
      /**
       * <pre>
       * 95 percentile.
       * </pre>
       *
       * <code>double q95 = 6;</code>
       * @param value The q95 to set.
       * @return This builder for chaining.
       */
      public Builder setQ95(double value) {
        
        q95_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 95 percentile.
       * </pre>
       *
       * <code>double q95 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ95() {
        
        q95_ = 0D;
        onChanged();
        return this;
      }

      private double q98_ ;
      /**
       * <pre>
       * 98 percentile.
       * </pre>
       *
       * <code>double q98 = 7;</code>
       * @return The q98.
       */
      @java.lang.Override
      public double getQ98() {
        return q98_;
      }
      /**
       * <pre>
       * 98 percentile.
       * </pre>
       *
       * <code>double q98 = 7;</code>
       * @param value The q98 to set.
       * @return This builder for chaining.
       */
      public Builder setQ98(double value) {
        
        q98_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 98 percentile.
       * </pre>
       *
       * <code>double q98 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ98() {
        
        q98_ = 0D;
        onChanged();
        return this;
      }

      private double q99_ ;
      /**
       * <pre>
       * 99 percentile.
       * </pre>
       *
       * <code>double q99 = 8;</code>
       * @return The q99.
       */
      @java.lang.Override
      public double getQ99() {
        return q99_;
      }
      /**
       * <pre>
       * 99 percentile.
       * </pre>
       *
       * <code>double q99 = 8;</code>
       * @param value The q99 to set.
       * @return This builder for chaining.
       */
      public Builder setQ99(double value) {
        
        q99_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 99 percentile.
       * </pre>
       *
       * <code>double q99 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ99() {
        
        q99_ = 0D;
        onChanged();
        return this;
      }

      private double q100_ ;
      /**
       * <pre>
       * 100 percentile (maximum or minimum).
       * </pre>
       *
       * <code>double q100 = 9;</code>
       * @return The q100.
       */
      @java.lang.Override
      public double getQ100() {
        return q100_;
      }
      /**
       * <pre>
       * 100 percentile (maximum or minimum).
       * </pre>
       *
       * <code>double q100 = 9;</code>
       * @param value The q100 to set.
       * @return This builder for chaining.
       */
      public Builder setQ100(double value) {
        
        q100_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 100 percentile (maximum or minimum).
       * </pre>
       *
       * <code>double q100 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearQ100() {
        
        q100_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yandex.cloud.loadtesting.api.v1.common.Quantiles)
    }

    // @@protoc_insertion_point(class_scope:yandex.cloud.loadtesting.api.v1.common.Quantiles)
    private static final yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles();
    }

    public static yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Quantiles>
        PARSER = new com.google.protobuf.AbstractParser<Quantiles>() {
      @java.lang.Override
      public Quantiles parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Quantiles(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Quantiles> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Quantiles> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yandex.cloud.api.loadtesting.api.v1.common.QuantilesOuterClass.Quantiles getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6yandex/cloud/loadtesting/api/v1/common" +
      "/quantiles.proto\022&yandex.cloud.loadtesti" +
      "ng.api.v1.common\"\201\001\n\tQuantiles\022\013\n\003q50\030\001 " +
      "\001(\001\022\013\n\003q75\030\002 \001(\001\022\013\n\003q80\030\003 \001(\001\022\013\n\003q85\030\004 \001" +
      "(\001\022\013\n\003q90\030\005 \001(\001\022\013\n\003q95\030\006 \001(\001\022\013\n\003q98\030\007 \001(" +
      "\001\022\013\n\003q99\030\010 \001(\001\022\014\n\004q100\030\t \001(\001B\177\n*yandex.c" +
      "loud.api.loadtesting.api.v1.commonZQgith" +
      "ub.com/yandex-cloud/go-genproto/yandex/c" +
      "loud/loadtesting/api/v1/common;commonb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yandex_cloud_loadtesting_api_v1_common_Quantiles_descriptor,
        new java.lang.String[] { "Q50", "Q75", "Q80", "Q85", "Q90", "Q95", "Q98", "Q99", "Q100", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
